# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/jinyee/FYP/RubikCube/190309Kociemba/kociemba/kociemba_hlx/kociemba_hlx.srcs/sources_1/bd/kociemba/ip/kociemba_processing_system7_0_0/kociemba_processing_system7_0_0.xci
# IP: The module: 'kociemba_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jinyee/FYP/RubikCube/190309Kociemba/kociemba/kociemba_hlx/kociemba_hlx.srcs/sources_1/bd/kociemba/ip/kociemba_processing_system7_0_0/kociemba_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'kociemba_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/jinyee/FYP/RubikCube/190309Kociemba/kociemba/kociemba_hlx/kociemba_hlx.srcs/sources_1/bd/kociemba/ip/kociemba_processing_system7_0_0/kociemba_processing_system7_0_0.xci
# IP: The module: 'kociemba_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jinyee/FYP/RubikCube/190309Kociemba/kociemba/kociemba_hlx/kociemba_hlx.srcs/sources_1/bd/kociemba/ip/kociemba_processing_system7_0_0/kociemba_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'kociemba_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
