// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module optimizeCube (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        moveCounter_V,
        moves_V_address0,
        moves_V_ce0,
        moves_V_we0,
        moves_V_d0,
        moves_V_q0,
        ap_return
);

parameter    ap_ST_fsm_state1 = 11'd1;
parameter    ap_ST_fsm_state2 = 11'd2;
parameter    ap_ST_fsm_state3 = 11'd4;
parameter    ap_ST_fsm_state4 = 11'd8;
parameter    ap_ST_fsm_state5 = 11'd16;
parameter    ap_ST_fsm_state6 = 11'd32;
parameter    ap_ST_fsm_state7 = 11'd64;
parameter    ap_ST_fsm_state8 = 11'd128;
parameter    ap_ST_fsm_state9 = 11'd256;
parameter    ap_ST_fsm_state10 = 11'd512;
parameter    ap_ST_fsm_state11 = 11'd1024;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] moveCounter_V;
output  [7:0] moves_V_address0;
output   moves_V_ce0;
output   moves_V_we0;
output  [3:0] moves_V_d0;
input  [3:0] moves_V_q0;
output  [7:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[7:0] moves_V_address0;
reg moves_V_ce0;
reg moves_V_we0;

(* fsm_encoding = "none" *) reg   [10:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    ap_CS_fsm_state2;
wire   [0:0] tmp_fu_175_p2;
reg   [3:0] moves_V_load_reg_417;
wire    ap_CS_fsm_state3;
wire   [0:0] r_V_fu_188_p1;
reg   [0:0] r_V_reg_427;
wire   [0:0] grp_fu_145_p2;
reg   [0:0] tmp_89_old_reg_436;
wire   [0:0] or_cond_fu_230_p2;
reg   [0:0] or_cond_reg_440;
wire    ap_CS_fsm_state4;
wire   [0:0] grp_fu_151_p2;
reg   [0:0] tmp_93_old_reg_444;
wire   [0:0] or_cond2_fu_270_p2;
reg   [0:0] or_cond2_reg_453;
wire    ap_CS_fsm_state5;
wire   [8:0] lhs_V_4_cast_fu_276_p1;
reg   [8:0] lhs_V_4_cast_reg_457;
wire   [0:0] grp_fu_156_p2;
reg   [0:0] tmp_73_reg_468;
wire    ap_CS_fsm_state6;
reg   [0:0] tmp_75_reg_477;
wire    ap_CS_fsm_state7;
reg   [0:0] tmp_77_reg_486;
wire    ap_CS_fsm_state8;
wire   [8:0] lhs_V_5_cast_fu_335_p1;
reg   [8:0] lhs_V_5_cast_reg_490;
reg   [0:0] tmp_80_reg_501;
wire    ap_CS_fsm_state9;
reg   [0:0] tmp_82_reg_510;
wire    ap_CS_fsm_state10;
wire   [7:0] i_V_3_fu_384_p2;
wire    ap_CS_fsm_state11;
reg   [7:0] p_s_reg_121;
wire   [7:0] i_V_2_fu_377_p2;
reg   [7:0] ap_phi_mux_t_V_1_phi_fu_136_p6;
reg   [7:0] t_V_1_reg_133;
wire   [7:0] i_V_fu_370_p2;
wire   [63:0] tmp_s_fu_180_p1;
wire   [63:0] tmp_66_fu_202_p1;
wire   [63:0] tmp_69_fu_246_p1;
wire   [63:0] tmp_72_fu_286_p1;
wire   [63:0] tmp_74_fu_296_p1;
wire   [63:0] tmp_76_fu_306_p1;
wire   [63:0] tmp_78_fu_320_p1;
wire   [63:0] tmp_79_fu_345_p1;
wire   [63:0] tmp_81_fu_355_p1;
wire   [63:0] tmp_83_fu_365_p1;
reg   [7:0] t_V_fu_28;
wire   [7:0] order_V_fu_314_p2;
reg   [7:0] order_V_1_fu_32;
reg   [3:0] grp_fu_145_p0;
wire   [8:0] lhs_V_1_cast_fu_192_p1;
wire   [8:0] r_V_2_fu_196_p2;
wire   [4:0] lhs_V_cast_fu_207_p1;
wire   [4:0] r_V_1_fu_210_p2;
wire   [5:0] r_V_1_cast_fu_216_p1;
wire   [5:0] tmp_83_cast_fu_220_p1;
wire   [0:0] tmp_67_fu_224_p2;
wire   [8:0] lhs_V_3_cast_fu_236_p1;
wire   [8:0] r_V_4_fu_240_p2;
wire   [4:0] lhs_V_2_cast_fu_251_p1;
wire   [4:0] r_V_3_fu_254_p2;
wire   [4:0] tmp_87_cast_fu_260_p1;
wire   [0:0] tmp_70_fu_264_p2;
wire   [8:0] r_V_5_fu_280_p2;
wire   [8:0] r_V_6_fu_291_p2;
wire   [8:0] r_V_7_fu_301_p2;
wire   [8:0] r_V_8_fu_339_p2;
wire   [8:0] r_V_9_fu_350_p2;
wire   [8:0] r_V_10_fu_360_p2;
reg   [10:0] ap_NS_fsm;
reg    ap_condition_219;
reg    ap_condition_241;

// power-on initialization
initial begin
#0 ap_CS_fsm = 11'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (((tmp_75_reg_477 == 1'd0) & (or_cond2_reg_453 == 1'd1) & (r_V_reg_427 == 1'd1)) | ((tmp_73_reg_468 == 1'd0) & (or_cond2_reg_453 == 1'd1) & (r_V_reg_427 == 1'd1)) | ((grp_fu_156_p2 == 1'd0) & (or_cond2_reg_453 == 1'd1) & (r_V_reg_427 == 1'd1)) | ((tmp_75_reg_477 == 1'd0) & (tmp_89_old_reg_436 == 1'd1) & (r_V_reg_427 == 1'd1)) | ((tmp_73_reg_468 == 1'd0) & (tmp_89_old_reg_436 == 1'd1) & (r_V_reg_427 == 1'd1)) | ((grp_fu_156_p2 == 1'd0) & (tmp_89_old_reg_436 == 1'd1) & (r_V_reg_427 == 1'd1)) | ((tmp_75_reg_477 == 1'd0) & (r_V_reg_427 == 1'd0) & (tmp_93_old_reg_444 == 1'd1)) | ((tmp_73_reg_468 == 1'd0) & (r_V_reg_427 == 1'd0) & (tmp_93_old_reg_444 == 1'd1)) | ((grp_fu_156_p2 == 1'd0) & (r_V_reg_427 == 1'd0) & (tmp_93_old_reg_444 == 1'd1)) | ((tmp_75_reg_477 == 1'd0) & (r_V_reg_427 == 1'd0) & (or_cond_reg_440 == 1'd1)) | ((tmp_73_reg_468 == 1'd0) & (r_V_reg_427 == 1'd0) & (or_cond_reg_440 == 1'd1)) | ((grp_fu_156_p2 == 1'd0) & (r_V_reg_427 == 1'd0) & (or_cond_reg_440 == 1'd1))))) begin
        order_V_1_fu_32 <= order_V_fu_314_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        order_V_1_fu_32 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        p_s_reg_121 <= i_V_3_fu_384_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        p_s_reg_121 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (((tmp_75_reg_477 == 1'd0) & (or_cond2_reg_453 == 1'd1) & (r_V_reg_427 == 1'd1)) | ((tmp_73_reg_468 == 1'd0) & (or_cond2_reg_453 == 1'd1) & (r_V_reg_427 == 1'd1)) | ((grp_fu_156_p2 == 1'd0) & (or_cond2_reg_453 == 1'd1) & (r_V_reg_427 == 1'd1)) | ((tmp_75_reg_477 == 1'd0) & (tmp_89_old_reg_436 == 1'd1) & (r_V_reg_427 == 1'd1)) | ((tmp_73_reg_468 == 1'd0) & (tmp_89_old_reg_436 == 1'd1) & (r_V_reg_427 == 1'd1)) | ((grp_fu_156_p2 == 1'd0) & (tmp_89_old_reg_436 == 1'd1) & (r_V_reg_427 == 1'd1)) | ((tmp_75_reg_477 == 1'd0) & (r_V_reg_427 == 1'd0) & (tmp_93_old_reg_444 == 1'd1)) | ((tmp_73_reg_468 == 1'd0) & (r_V_reg_427 == 1'd0) & (tmp_93_old_reg_444 == 1'd1)) | ((grp_fu_156_p2 == 1'd0) & (r_V_reg_427 == 1'd0) & (tmp_93_old_reg_444 == 1'd1)) | ((tmp_75_reg_477 == 1'd0) & (r_V_reg_427 == 1'd0) & (or_cond_reg_440 == 1'd1)) | ((tmp_73_reg_468 == 1'd0) & (r_V_reg_427 == 1'd0) & (or_cond_reg_440 == 1'd1)) | ((grp_fu_156_p2 == 1'd0) & (r_V_reg_427 == 1'd0) & (or_cond_reg_440 == 1'd1))))) begin
        t_V_1_reg_133 <= p_s_reg_121;
    end else if (((1'b1 == ap_CS_fsm_state11) & (((or_cond2_reg_453 == 1'd0) & (tmp_89_old_reg_436 == 1'd0) & (grp_fu_156_p2 == 1'd0) & (r_V_reg_427 == 1'd1)) | ((or_cond2_reg_453 == 1'd0) & (tmp_89_old_reg_436 == 1'd0) & (tmp_82_reg_510 == 1'd0) & (r_V_reg_427 == 1'd1)) | ((or_cond2_reg_453 == 1'd0) & (tmp_89_old_reg_436 == 1'd0) & (tmp_80_reg_501 == 1'd0) & (r_V_reg_427 == 1'd1)) | ((tmp_93_old_reg_444 == 1'd0) & (or_cond_reg_440 == 1'd0) & (grp_fu_156_p2 == 1'd0) & (r_V_reg_427 == 1'd0)) | ((tmp_93_old_reg_444 == 1'd0) & (or_cond_reg_440 == 1'd0) & (tmp_82_reg_510 == 1'd0) & (r_V_reg_427 == 1'd0)) | ((tmp_93_old_reg_444 == 1'd0) & (or_cond_reg_440 == 1'd0) & (tmp_80_reg_501 == 1'd0) & (r_V_reg_427 == 1'd0)) | ((grp_fu_156_p2 == 1'd0) & (tmp_77_reg_486 == 1'd1) & (tmp_75_reg_477 == 1'd1) & (tmp_73_reg_468 == 1'd1)) | ((tmp_82_reg_510 == 1'd0) & (tmp_77_reg_486 == 1'd1) & (tmp_75_reg_477 == 1'd1) & (tmp_73_reg_468 == 1'd1)) | ((tmp_80_reg_501 == 1'd0) & (tmp_77_reg_486 == 1'd1) & (tmp_75_reg_477 == 1'd1) & (tmp_73_reg_468 == 1'd1))))) begin
        t_V_1_reg_133 <= i_V_fu_370_p2;
    end else if (((1'b1 == ap_CS_fsm_state11) & (((or_cond2_reg_453 == 1'd0) & (tmp_89_old_reg_436 == 1'd0) & (r_V_reg_427 == 1'd1) & (tmp_82_reg_510 == 1'd1) & (tmp_80_reg_501 == 1'd1) & (grp_fu_156_p2 == 1'd1)) | ((tmp_93_old_reg_444 == 1'd0) & (or_cond_reg_440 == 1'd0) & (r_V_reg_427 == 1'd0) & (tmp_82_reg_510 == 1'd1) & (tmp_80_reg_501 == 1'd1) & (grp_fu_156_p2 == 1'd1)) | ((tmp_82_reg_510 == 1'd1) & (tmp_80_reg_501 == 1'd1) & (tmp_77_reg_486 == 1'd1) & (tmp_75_reg_477 == 1'd1) & (tmp_73_reg_468 == 1'd1) & (grp_fu_156_p2 == 1'd1))))) begin
        t_V_1_reg_133 <= i_V_2_fu_377_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (((tmp_75_reg_477 == 1'd0) & (or_cond2_reg_453 == 1'd1) & (r_V_reg_427 == 1'd1)) | ((tmp_73_reg_468 == 1'd0) & (or_cond2_reg_453 == 1'd1) & (r_V_reg_427 == 1'd1)) | ((grp_fu_156_p2 == 1'd0) & (or_cond2_reg_453 == 1'd1) & (r_V_reg_427 == 1'd1)) | ((tmp_75_reg_477 == 1'd0) & (tmp_89_old_reg_436 == 1'd1) & (r_V_reg_427 == 1'd1)) | ((tmp_73_reg_468 == 1'd0) & (tmp_89_old_reg_436 == 1'd1) & (r_V_reg_427 == 1'd1)) | ((grp_fu_156_p2 == 1'd0) & (tmp_89_old_reg_436 == 1'd1) & (r_V_reg_427 == 1'd1)) | ((tmp_75_reg_477 == 1'd0) & (r_V_reg_427 == 1'd0) & (tmp_93_old_reg_444 == 1'd1)) | ((tmp_73_reg_468 == 1'd0) & (r_V_reg_427 == 1'd0) & (tmp_93_old_reg_444 == 1'd1)) | ((grp_fu_156_p2 == 1'd0) & (r_V_reg_427 == 1'd0) & (tmp_93_old_reg_444 == 1'd1)) | ((tmp_75_reg_477 == 1'd0) & (r_V_reg_427 == 1'd0) & (or_cond_reg_440 == 1'd1)) | ((tmp_73_reg_468 == 1'd0) & (r_V_reg_427 == 1'd0) & (or_cond_reg_440 == 1'd1)) | ((grp_fu_156_p2 == 1'd0) & (r_V_reg_427 == 1'd0) & (or_cond_reg_440 == 1'd1))))) begin
        t_V_fu_28 <= order_V_fu_314_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        t_V_fu_28 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (((or_cond2_fu_270_p2 == 1'd1) & (r_V_reg_427 == 1'd1)) | ((tmp_89_old_reg_436 == 1'd1) & (r_V_reg_427 == 1'd1)) | ((r_V_reg_427 == 1'd0) & (tmp_93_old_reg_444 == 1'd1)) | ((r_V_reg_427 == 1'd0) & (or_cond_reg_440 == 1'd1))))) begin
        lhs_V_4_cast_reg_457[7 : 0] <= lhs_V_4_cast_fu_276_p1[7 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (((or_cond2_reg_453 == 1'd0) & (tmp_89_old_reg_436 == 1'd0) & (r_V_reg_427 == 1'd1)) | ((tmp_93_old_reg_444 == 1'd0) & (or_cond_reg_440 == 1'd0) & (r_V_reg_427 == 1'd0)) | ((tmp_75_reg_477 == 1'd1) & (tmp_73_reg_468 == 1'd1) & (grp_fu_156_p2 == 1'd1))))) begin
        lhs_V_5_cast_reg_490[7 : 0] <= lhs_V_5_cast_fu_335_p1[7 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        moves_V_load_reg_417 <= moves_V_q0;
        r_V_reg_427 <= r_V_fu_188_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_89_old_reg_436 == 1'd0) & (r_V_reg_427 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        or_cond2_reg_453 <= or_cond2_fu_270_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((r_V_reg_427 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        or_cond_reg_440 <= or_cond_fu_230_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        tmp_73_reg_468 <= grp_fu_156_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        tmp_75_reg_477 <= grp_fu_156_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (((or_cond2_reg_453 == 1'd1) & (r_V_reg_427 == 1'd1) & (tmp_75_reg_477 == 1'd1) & (tmp_73_reg_468 == 1'd1)) | ((tmp_89_old_reg_436 == 1'd1) & (r_V_reg_427 == 1'd1) & (tmp_75_reg_477 == 1'd1) & (tmp_73_reg_468 == 1'd1)) | ((r_V_reg_427 == 1'd0) & (tmp_93_old_reg_444 == 1'd1) & (tmp_75_reg_477 == 1'd1) & (tmp_73_reg_468 == 1'd1)) | ((r_V_reg_427 == 1'd0) & (or_cond_reg_440 == 1'd1) & (tmp_75_reg_477 == 1'd1) & (tmp_73_reg_468 == 1'd1))))) begin
        tmp_77_reg_486 <= grp_fu_156_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        tmp_80_reg_501 <= grp_fu_156_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        tmp_82_reg_510 <= grp_fu_156_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((r_V_fu_188_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        tmp_89_old_reg_436 <= grp_fu_145_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_fu_230_p2 == 1'd0) & (r_V_reg_427 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        tmp_93_old_reg_444 <= grp_fu_151_p2;
    end
end

always @ (*) begin
    if ((((tmp_fu_175_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        if ((1'b1 == ap_condition_241)) begin
            ap_phi_mux_t_V_1_phi_fu_136_p6 = i_V_fu_370_p2;
        end else if ((1'b1 == ap_condition_219)) begin
            ap_phi_mux_t_V_1_phi_fu_136_p6 = i_V_2_fu_377_p2;
        end else begin
            ap_phi_mux_t_V_1_phi_fu_136_p6 = t_V_1_reg_133;
        end
    end else begin
        ap_phi_mux_t_V_1_phi_fu_136_p6 = t_V_1_reg_133;
    end
end

always @ (*) begin
    if (((tmp_fu_175_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_145_p0 = moves_V_load_reg_417;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_145_p0 = moves_V_q0;
    end else begin
        grp_fu_145_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        moves_V_address0 = tmp_83_fu_365_p1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        moves_V_address0 = tmp_81_fu_355_p1;
    end else if (((1'b1 == ap_CS_fsm_state8) & (((or_cond2_reg_453 == 1'd0) & (tmp_89_old_reg_436 == 1'd0) & (r_V_reg_427 == 1'd1)) | ((tmp_93_old_reg_444 == 1'd0) & (or_cond_reg_440 == 1'd0) & (r_V_reg_427 == 1'd0)) | ((tmp_75_reg_477 == 1'd1) & (tmp_73_reg_468 == 1'd1) & (grp_fu_156_p2 == 1'd1))))) begin
        moves_V_address0 = tmp_79_fu_345_p1;
    end else if (((1'b1 == ap_CS_fsm_state8) & (((tmp_75_reg_477 == 1'd0) & (or_cond2_reg_453 == 1'd1) & (r_V_reg_427 == 1'd1)) | ((tmp_73_reg_468 == 1'd0) & (or_cond2_reg_453 == 1'd1) & (r_V_reg_427 == 1'd1)) | ((grp_fu_156_p2 == 1'd0) & (or_cond2_reg_453 == 1'd1) & (r_V_reg_427 == 1'd1)) | ((tmp_75_reg_477 == 1'd0) & (tmp_89_old_reg_436 == 1'd1) & (r_V_reg_427 == 1'd1)) | ((tmp_73_reg_468 == 1'd0) & (tmp_89_old_reg_436 == 1'd1) & (r_V_reg_427 == 1'd1)) | ((grp_fu_156_p2 == 1'd0) & (tmp_89_old_reg_436 == 1'd1) & (r_V_reg_427 == 1'd1)) | ((tmp_75_reg_477 == 1'd0) & (r_V_reg_427 == 1'd0) & (tmp_93_old_reg_444 == 1'd1)) | ((tmp_73_reg_468 == 1'd0) & (r_V_reg_427 == 1'd0) & (tmp_93_old_reg_444 == 1'd1)) | ((grp_fu_156_p2 == 1'd0) & (r_V_reg_427 == 1'd0) & (tmp_93_old_reg_444 == 1'd1)) | ((tmp_75_reg_477 == 1'd0) & (r_V_reg_427 == 1'd0) & (or_cond_reg_440 == 1'd1)) | ((tmp_73_reg_468 == 1'd0) & (r_V_reg_427 == 1'd0) & (or_cond_reg_440 == 1'd1)) | ((grp_fu_156_p2 == 1'd0) & (r_V_reg_427 == 1'd0) & (or_cond_reg_440 == 1'd1))))) begin
        moves_V_address0 = tmp_78_fu_320_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        moves_V_address0 = tmp_76_fu_306_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        moves_V_address0 = tmp_74_fu_296_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        moves_V_address0 = tmp_72_fu_286_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        moves_V_address0 = tmp_69_fu_246_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        moves_V_address0 = tmp_66_fu_202_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        moves_V_address0 = tmp_s_fu_180_p1;
    end else begin
        moves_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | ((1'b1 == ap_CS_fsm_state8) & (((tmp_75_reg_477 == 1'd0) & (or_cond2_reg_453 == 1'd1) & (r_V_reg_427 == 1'd1)) | ((tmp_73_reg_468 == 1'd0) & (or_cond2_reg_453 == 1'd1) & (r_V_reg_427 == 1'd1)) | ((grp_fu_156_p2 == 1'd0) & (or_cond2_reg_453 == 1'd1) & (r_V_reg_427 == 1'd1)) | ((tmp_75_reg_477 == 1'd0) & (tmp_89_old_reg_436 == 1'd1) & (r_V_reg_427 == 1'd1)) | ((tmp_73_reg_468 == 1'd0) & (tmp_89_old_reg_436 == 1'd1) & (r_V_reg_427 == 1'd1)) | ((grp_fu_156_p2 == 1'd0) & (tmp_89_old_reg_436 == 1'd1) & (r_V_reg_427 == 1'd1)) | ((tmp_75_reg_477 == 1'd0) & (r_V_reg_427 == 1'd0) & (tmp_93_old_reg_444 == 1'd1)) | ((tmp_73_reg_468 == 1'd0) & (r_V_reg_427 == 1'd0) & (tmp_93_old_reg_444 == 1'd1)) | ((grp_fu_156_p2 == 1'd0) & (r_V_reg_427 == 1'd0) & (tmp_93_old_reg_444 == 1'd1)) | ((tmp_75_reg_477 == 1'd0) & (r_V_reg_427 == 1'd0) & (or_cond_reg_440 == 1'd1)) | ((tmp_73_reg_468 == 1'd0) & (r_V_reg_427 == 1'd0) & (or_cond_reg_440 == 1'd1)) | ((grp_fu_156_p2 == 1'd0) & (r_V_reg_427 == 1'd0) & (or_cond_reg_440 == 1'd1)))) | ((1'b1 == ap_CS_fsm_state8) & (((or_cond2_reg_453 == 1'd0) & (tmp_89_old_reg_436 == 1'd0) & (r_V_reg_427 == 1'd1)) | ((tmp_93_old_reg_444 == 1'd0) & (or_cond_reg_440 == 1'd0) & (r_V_reg_427 == 1'd0)) | ((tmp_75_reg_477 == 1'd1) & (tmp_73_reg_468 == 1'd1) & (grp_fu_156_p2 == 1'd1)))))) begin
        moves_V_ce0 = 1'b1;
    end else begin
        moves_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) & (((tmp_75_reg_477 == 1'd0) & (or_cond2_reg_453 == 1'd1) & (r_V_reg_427 == 1'd1)) | ((tmp_73_reg_468 == 1'd0) & (or_cond2_reg_453 == 1'd1) & (r_V_reg_427 == 1'd1)) | ((grp_fu_156_p2 == 1'd0) & (or_cond2_reg_453 == 1'd1) & (r_V_reg_427 == 1'd1)) | ((tmp_75_reg_477 == 1'd0) & (tmp_89_old_reg_436 == 1'd1) & (r_V_reg_427 == 1'd1)) | ((tmp_73_reg_468 == 1'd0) & (tmp_89_old_reg_436 == 1'd1) & (r_V_reg_427 == 1'd1)) | ((grp_fu_156_p2 == 1'd0) & (tmp_89_old_reg_436 == 1'd1) & (r_V_reg_427 == 1'd1)) | ((tmp_75_reg_477 == 1'd0) & (r_V_reg_427 == 1'd0) & (tmp_93_old_reg_444 == 1'd1)) | ((tmp_73_reg_468 == 1'd0) & (r_V_reg_427 == 1'd0) & (tmp_93_old_reg_444 == 1'd1)) | ((grp_fu_156_p2 == 1'd0) & (r_V_reg_427 == 1'd0) & (tmp_93_old_reg_444 == 1'd1)) | ((tmp_75_reg_477 == 1'd0) & (r_V_reg_427 == 1'd0) & (or_cond_reg_440 == 1'd1)) | ((tmp_73_reg_468 == 1'd0) & (r_V_reg_427 == 1'd0) & (or_cond_reg_440 == 1'd1)) | ((grp_fu_156_p2 == 1'd0) & (r_V_reg_427 == 1'd0) & (or_cond_reg_440 == 1'd1))))) begin
        moves_V_we0 = 1'b1;
    end else begin
        moves_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((tmp_fu_175_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_fu_145_p2 == 1'd1) & (r_V_fu_188_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((grp_fu_151_p2 == 1'd0) & (or_cond_fu_230_p2 == 1'd0) & (r_V_reg_427 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((or_cond2_fu_270_p2 == 1'd0) & (tmp_89_old_reg_436 == 1'd0) & (r_V_reg_427 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((grp_fu_156_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (((tmp_75_reg_477 == 1'd0) & (or_cond2_reg_453 == 1'd1) & (r_V_reg_427 == 1'd1)) | ((tmp_73_reg_468 == 1'd0) & (or_cond2_reg_453 == 1'd1) & (r_V_reg_427 == 1'd1)) | ((grp_fu_156_p2 == 1'd0) & (or_cond2_reg_453 == 1'd1) & (r_V_reg_427 == 1'd1)) | ((tmp_75_reg_477 == 1'd0) & (tmp_89_old_reg_436 == 1'd1) & (r_V_reg_427 == 1'd1)) | ((tmp_73_reg_468 == 1'd0) & (tmp_89_old_reg_436 == 1'd1) & (r_V_reg_427 == 1'd1)) | ((grp_fu_156_p2 == 1'd0) & (tmp_89_old_reg_436 == 1'd1) & (r_V_reg_427 == 1'd1)) | ((tmp_75_reg_477 == 1'd0) & (r_V_reg_427 == 1'd0) & (tmp_93_old_reg_444 == 1'd1)) | ((tmp_73_reg_468 == 1'd0) & (r_V_reg_427 == 1'd0) & (tmp_93_old_reg_444 == 1'd1)) | ((grp_fu_156_p2 == 1'd0) & (r_V_reg_427 == 1'd0) & (tmp_93_old_reg_444 == 1'd1)) | ((tmp_75_reg_477 == 1'd0) & (r_V_reg_427 == 1'd0) & (or_cond_reg_440 == 1'd1)) | ((tmp_73_reg_468 == 1'd0) & (r_V_reg_427 == 1'd0) & (or_cond_reg_440 == 1'd1)) | ((grp_fu_156_p2 == 1'd0) & (r_V_reg_427 == 1'd0) & (or_cond_reg_440 == 1'd1))))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((grp_fu_156_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_condition_219 = (((or_cond2_reg_453 == 1'd0) & (tmp_89_old_reg_436 == 1'd0) & (r_V_reg_427 == 1'd1) & (tmp_82_reg_510 == 1'd1) & (tmp_80_reg_501 == 1'd1) & (grp_fu_156_p2 == 1'd1)) | ((tmp_93_old_reg_444 == 1'd0) & (or_cond_reg_440 == 1'd0) & (r_V_reg_427 == 1'd0) & (tmp_82_reg_510 == 1'd1) & (tmp_80_reg_501 == 1'd1) & (grp_fu_156_p2 == 1'd1)) | ((tmp_82_reg_510 == 1'd1) & (tmp_80_reg_501 == 1'd1) & (tmp_77_reg_486 == 1'd1) & (tmp_75_reg_477 == 1'd1) & (tmp_73_reg_468 == 1'd1) & (grp_fu_156_p2 == 1'd1)));
end

always @ (*) begin
    ap_condition_241 = (((or_cond2_reg_453 == 1'd0) & (tmp_89_old_reg_436 == 1'd0) & (grp_fu_156_p2 == 1'd0) & (r_V_reg_427 == 1'd1)) | ((or_cond2_reg_453 == 1'd0) & (tmp_89_old_reg_436 == 1'd0) & (tmp_82_reg_510 == 1'd0) & (r_V_reg_427 == 1'd1)) | ((or_cond2_reg_453 == 1'd0) & (tmp_89_old_reg_436 == 1'd0) & (tmp_80_reg_501 == 1'd0) & (r_V_reg_427 == 1'd1)) | ((tmp_93_old_reg_444 == 1'd0) & (or_cond_reg_440 == 1'd0) & (grp_fu_156_p2 == 1'd0) & (r_V_reg_427 == 1'd0)) | ((tmp_93_old_reg_444 == 1'd0) & (or_cond_reg_440 == 1'd0) & (tmp_82_reg_510 == 1'd0) & (r_V_reg_427 == 1'd0)) | ((tmp_93_old_reg_444 == 1'd0) & (or_cond_reg_440 == 1'd0) & (tmp_80_reg_501 == 1'd0) & (r_V_reg_427 == 1'd0)) | ((grp_fu_156_p2 == 1'd0) & (tmp_77_reg_486 == 1'd1) & (tmp_75_reg_477 == 1'd1) & (tmp_73_reg_468 == 1'd1)) | ((tmp_82_reg_510 == 1'd0) & (tmp_77_reg_486 == 1'd1) & (tmp_75_reg_477 == 1'd1) & (tmp_73_reg_468 == 1'd1)) | ((tmp_80_reg_501 == 1'd0) & (tmp_77_reg_486 == 1'd1) & (tmp_75_reg_477 == 1'd1) & (tmp_73_reg_468 == 1'd1)));
end

assign ap_return = order_V_1_fu_32;

assign grp_fu_145_p2 = ((grp_fu_145_p0 == 4'd12) ? 1'b1 : 1'b0);

assign grp_fu_151_p2 = ((moves_V_load_reg_417 == 4'd13) ? 1'b1 : 1'b0);

assign grp_fu_156_p2 = ((moves_V_load_reg_417 == moves_V_q0) ? 1'b1 : 1'b0);

assign i_V_2_fu_377_p2 = (p_s_reg_121 + 8'd3);

assign i_V_3_fu_384_p2 = (ap_phi_mux_t_V_1_phi_fu_136_p6 + 8'd1);

assign i_V_fu_370_p2 = (p_s_reg_121 + 8'd1);

assign lhs_V_1_cast_fu_192_p1 = p_s_reg_121;

assign lhs_V_2_cast_fu_251_p1 = moves_V_load_reg_417;

assign lhs_V_3_cast_fu_236_p1 = p_s_reg_121;

assign lhs_V_4_cast_fu_276_p1 = p_s_reg_121;

assign lhs_V_5_cast_fu_335_p1 = p_s_reg_121;

assign lhs_V_cast_fu_207_p1 = moves_V_load_reg_417;

assign moves_V_d0 = moves_V_load_reg_417;

assign or_cond2_fu_270_p2 = (tmp_70_fu_264_p2 | grp_fu_151_p2);

assign or_cond_fu_230_p2 = (tmp_67_fu_224_p2 | grp_fu_145_p2);

assign order_V_fu_314_p2 = (t_V_fu_28 + 8'd1);

assign r_V_10_fu_360_p2 = (lhs_V_5_cast_reg_490 + 9'd3);

assign r_V_1_cast_fu_216_p1 = r_V_1_fu_210_p2;

assign r_V_1_fu_210_p2 = (lhs_V_cast_fu_207_p1 + 5'd1);

assign r_V_2_fu_196_p2 = (lhs_V_1_cast_fu_192_p1 + 9'd1);

assign r_V_3_fu_254_p2 = ($signed(lhs_V_2_cast_fu_251_p1) + $signed(5'd31));

assign r_V_4_fu_240_p2 = (lhs_V_3_cast_fu_236_p1 + 9'd1);

assign r_V_5_fu_280_p2 = (lhs_V_4_cast_fu_276_p1 + 9'd1);

assign r_V_6_fu_291_p2 = (lhs_V_4_cast_reg_457 + 9'd2);

assign r_V_7_fu_301_p2 = (lhs_V_4_cast_reg_457 + 9'd3);

assign r_V_8_fu_339_p2 = (lhs_V_5_cast_fu_335_p1 + 9'd1);

assign r_V_9_fu_350_p2 = (lhs_V_5_cast_reg_490 + 9'd2);

assign r_V_fu_188_p1 = moves_V_q0[0:0];

assign tmp_66_fu_202_p1 = r_V_2_fu_196_p2;

assign tmp_67_fu_224_p2 = ((r_V_1_cast_fu_216_p1 != tmp_83_cast_fu_220_p1) ? 1'b1 : 1'b0);

assign tmp_69_fu_246_p1 = r_V_4_fu_240_p2;

assign tmp_70_fu_264_p2 = ((r_V_3_fu_254_p2 != tmp_87_cast_fu_260_p1) ? 1'b1 : 1'b0);

assign tmp_72_fu_286_p1 = r_V_5_fu_280_p2;

assign tmp_74_fu_296_p1 = r_V_6_fu_291_p2;

assign tmp_76_fu_306_p1 = r_V_7_fu_301_p2;

assign tmp_78_fu_320_p1 = t_V_fu_28;

assign tmp_79_fu_345_p1 = r_V_8_fu_339_p2;

assign tmp_81_fu_355_p1 = r_V_9_fu_350_p2;

assign tmp_83_cast_fu_220_p1 = moves_V_q0;

assign tmp_83_fu_365_p1 = r_V_10_fu_360_p2;

assign tmp_87_cast_fu_260_p1 = moves_V_q0;

assign tmp_fu_175_p2 = ((p_s_reg_121 < moveCounter_V) ? 1'b1 : 1'b0);

assign tmp_s_fu_180_p1 = p_s_reg_121;

always @ (posedge ap_clk) begin
    lhs_V_4_cast_reg_457[8] <= 1'b0;
    lhs_V_5_cast_reg_490[8] <= 1'b0;
end

endmodule //optimizeCube
