// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _getURtoUL_HH_
#define _getURtoUL_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "solution_sdiv_32nkbM.h"

namespace ap_rtl {

struct getURtoUL : public sc_module {
    // Port declarations 10
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<4> > cubiecube_0_ep_address0;
    sc_out< sc_logic > cubiecube_0_ep_ce0;
    sc_in< sc_lv<4> > cubiecube_0_ep_q0;
    sc_out< sc_lv<16> > ap_return;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    getURtoUL(sc_module_name name);
    SC_HAS_PROCESS(getURtoUL);

    ~getURtoUL();

    sc_trace_file* mVcdFile;

    solution_sdiv_32nkbM<1,36,32,32,32>* solution_sdiv_32nkbM_U41;
    sc_signal< sc_lv<47> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<32> > n_assign_cast5_fu_373_p1;
    sc_signal< sc_lv<32> > n_assign_cast5_reg_725;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<4> > j_4_fu_383_p2;
    sc_signal< sc_lv<4> > j_4_reg_735;
    sc_signal< sc_lv<1> > exitcond_fu_377_p2;
    sc_signal< sc_lv<4> > edge3_0_reg_766;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<1> > tmp_159_fu_409_p2;
    sc_signal< sc_lv<1> > tmp_159_reg_773;
    sc_signal< sc_lv<32> > x_1_fu_415_p2;
    sc_signal< sc_lv<32> > x_1_reg_777;
    sc_signal< sc_lv<32> > tmp_380_i_fu_459_p2;
    sc_signal< sc_lv<32> > tmp_380_i_reg_785;
    sc_signal< sc_lv<1> > tmp_i_fu_421_p2;
    sc_signal< sc_lv<32> > s_fu_470_p2;
    sc_signal< sc_lv<32> > s_reg_793;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<1> > exitcond_i_fu_465_p2;
    sc_signal< sc_lv<32> > i_24_fu_476_p2;
    sc_signal< sc_lv<32> > i_24_reg_798;
    sc_signal< sc_lv<32> > j_3_fu_487_p2;
    sc_signal< sc_lv<32> > j_3_reg_803;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<32> > grp_fu_482_p2;
    sc_signal< sc_logic > ap_CS_fsm_state40;
    sc_signal< sc_lv<5> > j_1_cast4_fu_516_p1;
    sc_signal< sc_lv<5> > j_1_cast4_reg_816;
    sc_signal< sc_logic > ap_CS_fsm_state42;
    sc_signal< sc_lv<1> > cond1_fu_526_p2;
    sc_signal< sc_lv<1> > cond1_reg_824;
    sc_signal< sc_lv<1> > tmp_160_fu_520_p2;
    sc_signal< sc_logic > ap_CS_fsm_state43;
    sc_signal< sc_lv<32> > k_1_fu_586_p2;
    sc_signal< sc_lv<32> > k_1_reg_844;
    sc_signal< sc_lv<2> > tmp_164_fu_592_p2;
    sc_signal< sc_lv<2> > tmp_164_reg_849;
    sc_signal< sc_lv<1> > tmp_163_fu_581_p2;
    sc_signal< sc_lv<2> > j_fu_598_p2;
    sc_signal< sc_lv<2> > j_reg_854;
    sc_signal< sc_lv<2> > i_25_fu_610_p2;
    sc_signal< sc_lv<2> > i_25_reg_862;
    sc_signal< sc_logic > ap_CS_fsm_state44;
    sc_signal< sc_lv<4> > arr_load_phi_i_fu_622_p3;
    sc_signal< sc_lv<1> > exitcond1_fu_604_p2;
    sc_signal< sc_lv<32> > tmp_165_fu_673_p2;
    sc_signal< sc_lv<32> > tmp_165_reg_874;
    sc_signal< sc_logic > ap_CS_fsm_state46;
    sc_signal< sc_lv<2> > indvars_iv_next_fu_679_p2;
    sc_signal< sc_lv<2> > indvars_iv_next_reg_879;
    sc_signal< sc_lv<32> > b_1_fu_685_p2;
    sc_signal< sc_logic > ap_CS_fsm_state47;
    sc_signal< sc_lv<4> > i_reg_103;
    sc_signal< sc_logic > ap_CS_fsm_state41;
    sc_signal< sc_lv<32> > j_i_reg_115;
    sc_signal< sc_lv<32> > i_i_reg_127;
    sc_signal< sc_lv<32> > s_i_reg_136;
    sc_signal< sc_lv<32> > p_0_i_reg_148;
    sc_signal< sc_lv<2> > indvars_iv_reg_160;
    sc_signal< sc_lv<2> > r_assign_reg_172;
    sc_signal< sc_lv<32> > b_reg_184;
    sc_signal< sc_lv<32> > k_reg_196;
    sc_signal< sc_lv<4> > arr2_i_reg_208;
    sc_signal< sc_logic > ap_CS_fsm_state45;
    sc_signal< sc_lv<1> > write_flag_i_reg_218;
    sc_signal< sc_lv<4> > arr1_i_reg_230;
    sc_signal< sc_lv<4> > arr_i_reg_240;
    sc_signal< sc_lv<2> > ap_phi_mux_i_i1_phi_fu_256_p4;
    sc_signal< sc_lv<2> > i_i1_reg_252;
    sc_signal< sc_lv<4> > arr2_i_be_reg_263;
    sc_signal< sc_lv<1> > write_flag_i_be_reg_278;
    sc_signal< sc_lv<4> > arr1_i_be_reg_295;
    sc_signal< sc_lv<4> > arr_i_be_reg_310;
    sc_signal< sc_lv<64> > tmp_s_fu_389_p1;
    sc_signal< sc_lv<4> > edge3_2_1_fu_58;
    sc_signal< sc_lv<2> > tmp_122_fu_500_p1;
    sc_signal< sc_lv<4> > edge3_2_2_fu_62;
    sc_signal< sc_lv<4> > edge3_2_3_fu_66;
    sc_signal< sc_lv<32> > a_1_1_fu_70;
    sc_signal< sc_lv<32> > a_1_fu_493_p2;
    sc_signal< sc_lv<32> > x_fu_74;
    sc_signal< sc_lv<4> > temp_fu_78;
    sc_signal< sc_lv<4> > edge3_0_1_fu_647_p3;
    sc_signal< sc_lv<4> > edge3_1_1_fu_82;
    sc_signal< sc_lv<4> > edge3_1_fu_640_p3;
    sc_signal< sc_lv<4> > edge3_2_4_fu_86;
    sc_signal< sc_lv<4> > edge3_2_fu_633_p3;
    sc_signal< sc_lv<3> > p_lshr_f_i_cast_fu_426_p4;
    sc_signal< sc_lv<32> > tmp_i_cast_fu_436_p1;
    sc_signal< sc_lv<1> > tmp_379_i_fu_440_p2;
    sc_signal< sc_lv<32> > k_assign_1_fu_446_p2;
    sc_signal< sc_lv<32> > p_k_i_fu_451_p3;
    sc_signal< sc_lv<32> > tmp_fu_532_p2;
    sc_signal< sc_lv<32> > tmp_119_fu_538_p2;
    sc_signal< sc_lv<32> > tmp_161_fu_544_p2;
    sc_signal< sc_lv<16> > tmp_121_fu_554_p1;
    sc_signal< sc_lv<16> > tmp_120_fu_550_p1;
    sc_signal< sc_lv<4> > edge3_load_phi_fu_570_p3;
    sc_signal< sc_lv<5> > tmp_199_cast_fu_577_p1;
    sc_signal< sc_lv<1> > cond_i_fu_616_p2;
    sc_signal< sc_lv<2> > tmp_165_fu_673_p0;
    sc_signal< sc_logic > grp_fu_482_ap_start;
    sc_signal< sc_logic > grp_fu_482_ap_done;
    sc_signal< sc_lv<16> > tmp_162_fu_558_p2;
    sc_signal< sc_lv<16> > ap_return_preg;
    sc_signal< sc_lv<47> > ap_NS_fsm;
    sc_signal< sc_lv<32> > tmp_165_fu_673_p00;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<47> ap_ST_fsm_state1;
    static const sc_lv<47> ap_ST_fsm_state2;
    static const sc_lv<47> ap_ST_fsm_state3;
    static const sc_lv<47> ap_ST_fsm_state4;
    static const sc_lv<47> ap_ST_fsm_state5;
    static const sc_lv<47> ap_ST_fsm_state6;
    static const sc_lv<47> ap_ST_fsm_state7;
    static const sc_lv<47> ap_ST_fsm_state8;
    static const sc_lv<47> ap_ST_fsm_state9;
    static const sc_lv<47> ap_ST_fsm_state10;
    static const sc_lv<47> ap_ST_fsm_state11;
    static const sc_lv<47> ap_ST_fsm_state12;
    static const sc_lv<47> ap_ST_fsm_state13;
    static const sc_lv<47> ap_ST_fsm_state14;
    static const sc_lv<47> ap_ST_fsm_state15;
    static const sc_lv<47> ap_ST_fsm_state16;
    static const sc_lv<47> ap_ST_fsm_state17;
    static const sc_lv<47> ap_ST_fsm_state18;
    static const sc_lv<47> ap_ST_fsm_state19;
    static const sc_lv<47> ap_ST_fsm_state20;
    static const sc_lv<47> ap_ST_fsm_state21;
    static const sc_lv<47> ap_ST_fsm_state22;
    static const sc_lv<47> ap_ST_fsm_state23;
    static const sc_lv<47> ap_ST_fsm_state24;
    static const sc_lv<47> ap_ST_fsm_state25;
    static const sc_lv<47> ap_ST_fsm_state26;
    static const sc_lv<47> ap_ST_fsm_state27;
    static const sc_lv<47> ap_ST_fsm_state28;
    static const sc_lv<47> ap_ST_fsm_state29;
    static const sc_lv<47> ap_ST_fsm_state30;
    static const sc_lv<47> ap_ST_fsm_state31;
    static const sc_lv<47> ap_ST_fsm_state32;
    static const sc_lv<47> ap_ST_fsm_state33;
    static const sc_lv<47> ap_ST_fsm_state34;
    static const sc_lv<47> ap_ST_fsm_state35;
    static const sc_lv<47> ap_ST_fsm_state36;
    static const sc_lv<47> ap_ST_fsm_state37;
    static const sc_lv<47> ap_ST_fsm_state38;
    static const sc_lv<47> ap_ST_fsm_state39;
    static const sc_lv<47> ap_ST_fsm_state40;
    static const sc_lv<47> ap_ST_fsm_state41;
    static const sc_lv<47> ap_ST_fsm_state42;
    static const sc_lv<47> ap_ST_fsm_state43;
    static const sc_lv<47> ap_ST_fsm_state44;
    static const sc_lv<47> ap_ST_fsm_state45;
    static const sc_lv<47> ap_ST_fsm_state46;
    static const sc_lv<47> ap_ST_fsm_state47;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_27;
    static const sc_lv<32> ap_const_lv32_29;
    static const sc_lv<32> ap_const_lv32_2A;
    static const sc_lv<32> ap_const_lv32_2B;
    static const sc_lv<32> ap_const_lv32_2D;
    static const sc_lv<32> ap_const_lv32_2E;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<32> ap_const_lv32_28;
    static const sc_lv<2> ap_const_lv2_2;
    static const sc_lv<32> ap_const_lv32_2C;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<4> ap_const_lv4_C;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<4> ap_const_lv4_3;
    static const sc_lv<32> ap_const_lv32_FFFFFFFF;
    static const sc_lv<2> ap_const_lv2_3;
    static const sc_lv<16> ap_const_lv16_0;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_a_1_fu_493_p2();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state40();
    void thread_ap_CS_fsm_state41();
    void thread_ap_CS_fsm_state42();
    void thread_ap_CS_fsm_state43();
    void thread_ap_CS_fsm_state44();
    void thread_ap_CS_fsm_state45();
    void thread_ap_CS_fsm_state46();
    void thread_ap_CS_fsm_state47();
    void thread_ap_CS_fsm_state5();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_phi_mux_i_i1_phi_fu_256_p4();
    void thread_ap_ready();
    void thread_ap_return();
    void thread_arr_load_phi_i_fu_622_p3();
    void thread_b_1_fu_685_p2();
    void thread_cond1_fu_526_p2();
    void thread_cond_i_fu_616_p2();
    void thread_cubiecube_0_ep_address0();
    void thread_cubiecube_0_ep_ce0();
    void thread_edge3_0_1_fu_647_p3();
    void thread_edge3_1_fu_640_p3();
    void thread_edge3_2_fu_633_p3();
    void thread_edge3_load_phi_fu_570_p3();
    void thread_exitcond1_fu_604_p2();
    void thread_exitcond_fu_377_p2();
    void thread_exitcond_i_fu_465_p2();
    void thread_grp_fu_482_ap_start();
    void thread_i_24_fu_476_p2();
    void thread_i_25_fu_610_p2();
    void thread_indvars_iv_next_fu_679_p2();
    void thread_j_1_cast4_fu_516_p1();
    void thread_j_3_fu_487_p2();
    void thread_j_4_fu_383_p2();
    void thread_j_fu_598_p2();
    void thread_k_1_fu_586_p2();
    void thread_k_assign_1_fu_446_p2();
    void thread_n_assign_cast5_fu_373_p1();
    void thread_p_k_i_fu_451_p3();
    void thread_p_lshr_f_i_cast_fu_426_p4();
    void thread_s_fu_470_p2();
    void thread_tmp_119_fu_538_p2();
    void thread_tmp_120_fu_550_p1();
    void thread_tmp_121_fu_554_p1();
    void thread_tmp_122_fu_500_p1();
    void thread_tmp_159_fu_409_p2();
    void thread_tmp_160_fu_520_p2();
    void thread_tmp_161_fu_544_p2();
    void thread_tmp_162_fu_558_p2();
    void thread_tmp_163_fu_581_p2();
    void thread_tmp_164_fu_592_p2();
    void thread_tmp_165_fu_673_p0();
    void thread_tmp_165_fu_673_p00();
    void thread_tmp_165_fu_673_p2();
    void thread_tmp_199_cast_fu_577_p1();
    void thread_tmp_379_i_fu_440_p2();
    void thread_tmp_380_i_fu_459_p2();
    void thread_tmp_fu_532_p2();
    void thread_tmp_i_cast_fu_436_p1();
    void thread_tmp_i_fu_421_p2();
    void thread_tmp_s_fu_389_p1();
    void thread_x_1_fu_415_p2();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
