// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "getUBtoDF.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic getUBtoDF::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic getUBtoDF::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<47> getUBtoDF::ap_ST_fsm_state1 = "1";
const sc_lv<47> getUBtoDF::ap_ST_fsm_state2 = "10";
const sc_lv<47> getUBtoDF::ap_ST_fsm_state3 = "100";
const sc_lv<47> getUBtoDF::ap_ST_fsm_state4 = "1000";
const sc_lv<47> getUBtoDF::ap_ST_fsm_state5 = "10000";
const sc_lv<47> getUBtoDF::ap_ST_fsm_state6 = "100000";
const sc_lv<47> getUBtoDF::ap_ST_fsm_state7 = "1000000";
const sc_lv<47> getUBtoDF::ap_ST_fsm_state8 = "10000000";
const sc_lv<47> getUBtoDF::ap_ST_fsm_state9 = "100000000";
const sc_lv<47> getUBtoDF::ap_ST_fsm_state10 = "1000000000";
const sc_lv<47> getUBtoDF::ap_ST_fsm_state11 = "10000000000";
const sc_lv<47> getUBtoDF::ap_ST_fsm_state12 = "100000000000";
const sc_lv<47> getUBtoDF::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<47> getUBtoDF::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<47> getUBtoDF::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<47> getUBtoDF::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<47> getUBtoDF::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<47> getUBtoDF::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<47> getUBtoDF::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<47> getUBtoDF::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<47> getUBtoDF::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<47> getUBtoDF::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<47> getUBtoDF::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<47> getUBtoDF::ap_ST_fsm_state24 = "100000000000000000000000";
const sc_lv<47> getUBtoDF::ap_ST_fsm_state25 = "1000000000000000000000000";
const sc_lv<47> getUBtoDF::ap_ST_fsm_state26 = "10000000000000000000000000";
const sc_lv<47> getUBtoDF::ap_ST_fsm_state27 = "100000000000000000000000000";
const sc_lv<47> getUBtoDF::ap_ST_fsm_state28 = "1000000000000000000000000000";
const sc_lv<47> getUBtoDF::ap_ST_fsm_state29 = "10000000000000000000000000000";
const sc_lv<47> getUBtoDF::ap_ST_fsm_state30 = "100000000000000000000000000000";
const sc_lv<47> getUBtoDF::ap_ST_fsm_state31 = "1000000000000000000000000000000";
const sc_lv<47> getUBtoDF::ap_ST_fsm_state32 = "10000000000000000000000000000000";
const sc_lv<47> getUBtoDF::ap_ST_fsm_state33 = "100000000000000000000000000000000";
const sc_lv<47> getUBtoDF::ap_ST_fsm_state34 = "1000000000000000000000000000000000";
const sc_lv<47> getUBtoDF::ap_ST_fsm_state35 = "10000000000000000000000000000000000";
const sc_lv<47> getUBtoDF::ap_ST_fsm_state36 = "100000000000000000000000000000000000";
const sc_lv<47> getUBtoDF::ap_ST_fsm_state37 = "1000000000000000000000000000000000000";
const sc_lv<47> getUBtoDF::ap_ST_fsm_state38 = "10000000000000000000000000000000000000";
const sc_lv<47> getUBtoDF::ap_ST_fsm_state39 = "100000000000000000000000000000000000000";
const sc_lv<47> getUBtoDF::ap_ST_fsm_state40 = "1000000000000000000000000000000000000000";
const sc_lv<47> getUBtoDF::ap_ST_fsm_state41 = "10000000000000000000000000000000000000000";
const sc_lv<47> getUBtoDF::ap_ST_fsm_state42 = "100000000000000000000000000000000000000000";
const sc_lv<47> getUBtoDF::ap_ST_fsm_state43 = "1000000000000000000000000000000000000000000";
const sc_lv<47> getUBtoDF::ap_ST_fsm_state44 = "10000000000000000000000000000000000000000000";
const sc_lv<47> getUBtoDF::ap_ST_fsm_state45 = "100000000000000000000000000000000000000000000";
const sc_lv<47> getUBtoDF::ap_ST_fsm_state46 = "1000000000000000000000000000000000000000000000";
const sc_lv<47> getUBtoDF::ap_ST_fsm_state47 = "10000000000000000000000000000000000000000000000";
const sc_lv<32> getUBtoDF::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> getUBtoDF::ap_const_lv32_1 = "1";
const sc_lv<1> getUBtoDF::ap_const_lv1_0 = "0";
const sc_lv<32> getUBtoDF::ap_const_lv32_2 = "10";
const sc_lv<1> getUBtoDF::ap_const_lv1_1 = "1";
const sc_lv<32> getUBtoDF::ap_const_lv32_3 = "11";
const sc_lv<32> getUBtoDF::ap_const_lv32_4 = "100";
const sc_lv<32> getUBtoDF::ap_const_lv32_27 = "100111";
const sc_lv<32> getUBtoDF::ap_const_lv32_29 = "101001";
const sc_lv<32> getUBtoDF::ap_const_lv32_2A = "101010";
const sc_lv<32> getUBtoDF::ap_const_lv32_2B = "101011";
const sc_lv<32> getUBtoDF::ap_const_lv32_2D = "101101";
const sc_lv<32> getUBtoDF::ap_const_lv32_2E = "101110";
const sc_lv<4> getUBtoDF::ap_const_lv4_0 = "0000";
const sc_lv<32> getUBtoDF::ap_const_lv32_28 = "101000";
const sc_lv<2> getUBtoDF::ap_const_lv2_2 = "10";
const sc_lv<32> getUBtoDF::ap_const_lv32_2C = "101100";
const sc_lv<2> getUBtoDF::ap_const_lv2_0 = "00";
const sc_lv<2> getUBtoDF::ap_const_lv2_1 = "1";
const sc_lv<4> getUBtoDF::ap_const_lv4_C = "1100";
const sc_lv<4> getUBtoDF::ap_const_lv4_1 = "1";
const sc_lv<4> getUBtoDF::ap_const_lv4_2 = "10";
const sc_lv<4> getUBtoDF::ap_const_lv4_6 = "110";
const sc_lv<32> getUBtoDF::ap_const_lv32_FFFFFFFF = "11111111111111111111111111111111";
const sc_lv<3> getUBtoDF::ap_const_lv3_3 = "11";
const sc_lv<2> getUBtoDF::ap_const_lv2_3 = "11";
const sc_lv<16> getUBtoDF::ap_const_lv16_0 = "0000000000000000";
const bool getUBtoDF::ap_const_boolean_1 = true;

getUBtoDF::getUBtoDF(sc_module_name name) : sc_module(name), mVcdFile(0) {
    solution_sdiv_32nkbM_U43 = new solution_sdiv_32nkbM<1,36,32,32,32>("solution_sdiv_32nkbM_U43");
    solution_sdiv_32nkbM_U43->clk(ap_clk);
    solution_sdiv_32nkbM_U43->reset(ap_rst);
    solution_sdiv_32nkbM_U43->start(grp_fu_498_ap_start);
    solution_sdiv_32nkbM_U43->done(grp_fu_498_ap_done);
    solution_sdiv_32nkbM_U43->din0(s_reg_819);
    solution_sdiv_32nkbM_U43->din1(j_i_reg_119);
    solution_sdiv_32nkbM_U43->ce(ap_var_for_const0);
    solution_sdiv_32nkbM_U43->dout(grp_fu_498_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_a_3_fu_509_p2);
    sensitive << ( p_0_i_reg_152 );
    sensitive << ( a_1_fu_74 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state40);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state41);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state42);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state43);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state44);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state45);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state46);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state47);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state42 );
    sensitive << ( tmp_184_fu_536_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_phi_mux_i_i1_phi_fu_260_p4);
    sensitive << ( i_i1_reg_256 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state42 );
    sensitive << ( tmp_184_fu_536_p2 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_CS_fsm_state42 );
    sensitive << ( tmp_184_fu_536_p2 );
    sensitive << ( tmp_186_fu_584_p2 );
    sensitive << ( ap_return_preg );

    SC_METHOD(thread_arr_load_phi_i_fu_648_p3);
    sensitive << ( arr2_i_reg_212 );
    sensitive << ( arr1_i_reg_234 );
    sensitive << ( cond_i_fu_642_p2 );

    SC_METHOD(thread_b_3_fu_711_p2);
    sensitive << ( tmp_190_reg_900 );
    sensitive << ( k_reg_200 );

    SC_METHOD(thread_cond2_fu_552_p2);
    sensitive << ( ap_CS_fsm_state42 );
    sensitive << ( tmp_184_fu_536_p2 );
    sensitive << ( r_assign_reg_176 );

    SC_METHOD(thread_cond_i_fu_642_p2);
    sensitive << ( ap_CS_fsm_state44 );
    sensitive << ( exitcond1_fu_630_p2 );
    sensitive << ( i_i1_reg_256 );

    SC_METHOD(thread_cubiecube_0_ep_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_s_fu_393_p1 );

    SC_METHOD(thread_cubiecube_0_ep_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_edge3_0_2_fu_673_p3);
    sensitive << ( write_flag_i_reg_222 );
    sensitive << ( arr_i_reg_244 );
    sensitive << ( temp_fu_82 );

    SC_METHOD(thread_edge3_1_fu_666_p3);
    sensitive << ( cond2_reg_850 );
    sensitive << ( arr1_i_reg_234 );
    sensitive << ( temp_fu_82 );

    SC_METHOD(thread_edge3_2_fu_659_p3);
    sensitive << ( cond2_reg_850 );
    sensitive << ( arr2_i_reg_212 );
    sensitive << ( temp_fu_82 );

    SC_METHOD(thread_edge3_load_phi_fu_596_p3);
    sensitive << ( cond2_reg_850 );
    sensitive << ( edge3_1_3_fu_86 );
    sensitive << ( edge3_2_9_fu_90 );

    SC_METHOD(thread_exitcond1_fu_630_p2);
    sensitive << ( ap_CS_fsm_state44 );
    sensitive << ( indvars_iv_reg_164 );
    sensitive << ( i_i1_reg_256 );

    SC_METHOD(thread_exitcond_fu_381_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_reg_107 );

    SC_METHOD(thread_exitcond_i_fu_481_p2);
    sensitive << ( tmp_380_i_reg_811 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( j_i_reg_119 );

    SC_METHOD(thread_grp_fu_498_ap_start);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_i_28_fu_492_p2);
    sensitive << ( i_i_reg_131 );

    SC_METHOD(thread_i_29_fu_636_p2);
    sensitive << ( i_i1_reg_256 );

    SC_METHOD(thread_indvars_iv_next_fu_705_p2);
    sensitive << ( indvars_iv_reg_164 );

    SC_METHOD(thread_j_10_fu_387_p2);
    sensitive << ( i_reg_107 );

    SC_METHOD(thread_j_1_cast_fu_532_p1);
    sensitive << ( r_assign_reg_176 );

    SC_METHOD(thread_j_9_fu_503_p2);
    sensitive << ( j_i_reg_119 );

    SC_METHOD(thread_j_fu_624_p2);
    sensitive << ( r_assign_reg_176 );

    SC_METHOD(thread_k_3_fu_612_p2);
    sensitive << ( k_reg_200 );

    SC_METHOD(thread_k_assign_3_fu_462_p2);
    sensitive << ( n_assign_cast4_reg_751 );
    sensitive << ( x_4_fu_431_p2 );

    SC_METHOD(thread_n_assign_cast4_fu_377_p1);
    sensitive << ( i_reg_107 );

    SC_METHOD(thread_or_cond_fu_425_p2);
    sensitive << ( tmp_182_fu_413_p2 );
    sensitive << ( tmp_183_fu_419_p2 );

    SC_METHOD(thread_p_k_i_fu_467_p3);
    sensitive << ( x_4_fu_431_p2 );
    sensitive << ( tmp_379_i_fu_456_p2 );
    sensitive << ( k_assign_3_fu_462_p2 );

    SC_METHOD(thread_p_lshr_f_i_cast_fu_442_p4);
    sensitive << ( i_reg_107 );

    SC_METHOD(thread_s_fu_486_p2);
    sensitive << ( i_i_reg_131 );
    sensitive << ( s_i_reg_140 );

    SC_METHOD(thread_tmp_123_fu_564_p2);
    sensitive << ( a_1_fu_74 );

    SC_METHOD(thread_tmp_124_fu_576_p1);
    sensitive << ( b_reg_188 );

    SC_METHOD(thread_tmp_125_fu_580_p1);
    sensitive << ( tmp_185_fu_570_p2 );

    SC_METHOD(thread_tmp_126_fu_516_p1);
    sensitive << ( x_fu_78 );

    SC_METHOD(thread_tmp_182_fu_413_p2);
    sensitive << ( cubiecube_0_ep_q0 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_tmp_183_fu_419_p2);
    sensitive << ( cubiecube_0_ep_q0 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_tmp_184_fu_536_p2);
    sensitive << ( ap_CS_fsm_state42 );
    sensitive << ( r_assign_reg_176 );

    SC_METHOD(thread_tmp_185_fu_570_p2);
    sensitive << ( tmp_fu_558_p2 );
    sensitive << ( tmp_123_fu_564_p2 );

    SC_METHOD(thread_tmp_186_fu_584_p2);
    sensitive << ( tmp_125_fu_580_p1 );
    sensitive << ( tmp_124_fu_576_p1 );

    SC_METHOD(thread_tmp_187_fu_542_p2);
    sensitive << ( j_1_cast_fu_532_p1 );

    SC_METHOD(thread_tmp_188_fu_607_p2);
    sensitive << ( tmp_225_cast_reg_845 );
    sensitive << ( ap_CS_fsm_state43 );
    sensitive << ( tmp_228_cast_fu_603_p1 );

    SC_METHOD(thread_tmp_189_fu_618_p2);
    sensitive << ( r_assign_reg_176 );

    SC_METHOD(thread_tmp_190_fu_699_p0);
    sensitive << ( ap_CS_fsm_state46 );
    sensitive << ( tmp_190_fu_699_p00 );

    SC_METHOD(thread_tmp_190_fu_699_p00);
    sensitive << ( tmp_189_reg_875 );

    SC_METHOD(thread_tmp_190_fu_699_p2);
    sensitive << ( b_reg_188 );
    sensitive << ( tmp_190_fu_699_p0 );

    SC_METHOD(thread_tmp_225_cast_fu_548_p1);
    sensitive << ( tmp_187_fu_542_p2 );

    SC_METHOD(thread_tmp_228_cast_fu_603_p1);
    sensitive << ( edge3_load_phi_fu_596_p3 );

    SC_METHOD(thread_tmp_379_i_fu_456_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( or_cond_fu_425_p2 );
    sensitive << ( x_4_fu_431_p2 );
    sensitive << ( tmp_i_fu_437_p2 );
    sensitive << ( tmp_i_cast_fu_452_p1 );

    SC_METHOD(thread_tmp_380_i_fu_475_p2);
    sensitive << ( p_k_i_fu_467_p3 );

    SC_METHOD(thread_tmp_fu_558_p2);
    sensitive << ( a_1_fu_74 );

    SC_METHOD(thread_tmp_i_cast_fu_452_p1);
    sensitive << ( p_lshr_f_i_cast_fu_442_p4 );

    SC_METHOD(thread_tmp_i_fu_437_p2);
    sensitive << ( n_assign_cast4_reg_751 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( or_cond_fu_425_p2 );
    sensitive << ( x_4_fu_431_p2 );

    SC_METHOD(thread_tmp_s_fu_393_p1);
    sensitive << ( i_reg_107 );

    SC_METHOD(thread_x_4_fu_431_p2);
    sensitive << ( x_fu_78 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_fu_381_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( or_cond_fu_425_p2 );
    sensitive << ( tmp_i_fu_437_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond_i_fu_481_p2 );
    sensitive << ( ap_CS_fsm_state42 );
    sensitive << ( tmp_184_fu_536_p2 );
    sensitive << ( ap_CS_fsm_state43 );
    sensitive << ( tmp_188_fu_607_p2 );
    sensitive << ( ap_CS_fsm_state44 );
    sensitive << ( exitcond1_fu_630_p2 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "00000000000000000000000000000000000000000000001";
    ap_return_preg = "0000000000000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "getUBtoDF_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, cubiecube_0_ep_address0, "(port)cubiecube_0_ep_address0");
    sc_trace(mVcdFile, cubiecube_0_ep_ce0, "(port)cubiecube_0_ep_ce0");
    sc_trace(mVcdFile, cubiecube_0_ep_q0, "(port)cubiecube_0_ep_q0");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, n_assign_cast4_fu_377_p1, "n_assign_cast4_fu_377_p1");
    sc_trace(mVcdFile, n_assign_cast4_reg_751, "n_assign_cast4_reg_751");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, j_10_fu_387_p2, "j_10_fu_387_p2");
    sc_trace(mVcdFile, j_10_reg_761, "j_10_reg_761");
    sc_trace(mVcdFile, exitcond_fu_381_p2, "exitcond_fu_381_p2");
    sc_trace(mVcdFile, edge3_0_reg_792, "edge3_0_reg_792");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, or_cond_fu_425_p2, "or_cond_fu_425_p2");
    sc_trace(mVcdFile, or_cond_reg_799, "or_cond_reg_799");
    sc_trace(mVcdFile, x_4_fu_431_p2, "x_4_fu_431_p2");
    sc_trace(mVcdFile, x_4_reg_803, "x_4_reg_803");
    sc_trace(mVcdFile, tmp_380_i_fu_475_p2, "tmp_380_i_fu_475_p2");
    sc_trace(mVcdFile, tmp_380_i_reg_811, "tmp_380_i_reg_811");
    sc_trace(mVcdFile, tmp_i_fu_437_p2, "tmp_i_fu_437_p2");
    sc_trace(mVcdFile, s_fu_486_p2, "s_fu_486_p2");
    sc_trace(mVcdFile, s_reg_819, "s_reg_819");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, exitcond_i_fu_481_p2, "exitcond_i_fu_481_p2");
    sc_trace(mVcdFile, i_28_fu_492_p2, "i_28_fu_492_p2");
    sc_trace(mVcdFile, i_28_reg_824, "i_28_reg_824");
    sc_trace(mVcdFile, j_9_fu_503_p2, "j_9_fu_503_p2");
    sc_trace(mVcdFile, j_9_reg_829, "j_9_reg_829");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, grp_fu_498_p2, "grp_fu_498_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state40, "ap_CS_fsm_state40");
    sc_trace(mVcdFile, tmp_225_cast_fu_548_p1, "tmp_225_cast_fu_548_p1");
    sc_trace(mVcdFile, tmp_225_cast_reg_845, "tmp_225_cast_reg_845");
    sc_trace(mVcdFile, ap_CS_fsm_state42, "ap_CS_fsm_state42");
    sc_trace(mVcdFile, tmp_184_fu_536_p2, "tmp_184_fu_536_p2");
    sc_trace(mVcdFile, cond2_fu_552_p2, "cond2_fu_552_p2");
    sc_trace(mVcdFile, cond2_reg_850, "cond2_reg_850");
    sc_trace(mVcdFile, ap_CS_fsm_state43, "ap_CS_fsm_state43");
    sc_trace(mVcdFile, k_3_fu_612_p2, "k_3_fu_612_p2");
    sc_trace(mVcdFile, k_3_reg_870, "k_3_reg_870");
    sc_trace(mVcdFile, tmp_189_fu_618_p2, "tmp_189_fu_618_p2");
    sc_trace(mVcdFile, tmp_189_reg_875, "tmp_189_reg_875");
    sc_trace(mVcdFile, tmp_188_fu_607_p2, "tmp_188_fu_607_p2");
    sc_trace(mVcdFile, j_fu_624_p2, "j_fu_624_p2");
    sc_trace(mVcdFile, j_reg_880, "j_reg_880");
    sc_trace(mVcdFile, i_29_fu_636_p2, "i_29_fu_636_p2");
    sc_trace(mVcdFile, i_29_reg_888, "i_29_reg_888");
    sc_trace(mVcdFile, ap_CS_fsm_state44, "ap_CS_fsm_state44");
    sc_trace(mVcdFile, arr_load_phi_i_fu_648_p3, "arr_load_phi_i_fu_648_p3");
    sc_trace(mVcdFile, exitcond1_fu_630_p2, "exitcond1_fu_630_p2");
    sc_trace(mVcdFile, tmp_190_fu_699_p2, "tmp_190_fu_699_p2");
    sc_trace(mVcdFile, tmp_190_reg_900, "tmp_190_reg_900");
    sc_trace(mVcdFile, ap_CS_fsm_state46, "ap_CS_fsm_state46");
    sc_trace(mVcdFile, indvars_iv_next_fu_705_p2, "indvars_iv_next_fu_705_p2");
    sc_trace(mVcdFile, indvars_iv_next_reg_905, "indvars_iv_next_reg_905");
    sc_trace(mVcdFile, b_3_fu_711_p2, "b_3_fu_711_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state47, "ap_CS_fsm_state47");
    sc_trace(mVcdFile, i_reg_107, "i_reg_107");
    sc_trace(mVcdFile, ap_CS_fsm_state41, "ap_CS_fsm_state41");
    sc_trace(mVcdFile, j_i_reg_119, "j_i_reg_119");
    sc_trace(mVcdFile, i_i_reg_131, "i_i_reg_131");
    sc_trace(mVcdFile, s_i_reg_140, "s_i_reg_140");
    sc_trace(mVcdFile, p_0_i_reg_152, "p_0_i_reg_152");
    sc_trace(mVcdFile, indvars_iv_reg_164, "indvars_iv_reg_164");
    sc_trace(mVcdFile, r_assign_reg_176, "r_assign_reg_176");
    sc_trace(mVcdFile, b_reg_188, "b_reg_188");
    sc_trace(mVcdFile, k_reg_200, "k_reg_200");
    sc_trace(mVcdFile, arr2_i_reg_212, "arr2_i_reg_212");
    sc_trace(mVcdFile, ap_CS_fsm_state45, "ap_CS_fsm_state45");
    sc_trace(mVcdFile, write_flag_i_reg_222, "write_flag_i_reg_222");
    sc_trace(mVcdFile, arr1_i_reg_234, "arr1_i_reg_234");
    sc_trace(mVcdFile, arr_i_reg_244, "arr_i_reg_244");
    sc_trace(mVcdFile, ap_phi_mux_i_i1_phi_fu_260_p4, "ap_phi_mux_i_i1_phi_fu_260_p4");
    sc_trace(mVcdFile, i_i1_reg_256, "i_i1_reg_256");
    sc_trace(mVcdFile, arr2_i_be_reg_267, "arr2_i_be_reg_267");
    sc_trace(mVcdFile, write_flag_i_be_reg_282, "write_flag_i_be_reg_282");
    sc_trace(mVcdFile, arr1_i_be_reg_299, "arr1_i_be_reg_299");
    sc_trace(mVcdFile, arr_i_be_reg_314, "arr_i_be_reg_314");
    sc_trace(mVcdFile, tmp_s_fu_393_p1, "tmp_s_fu_393_p1");
    sc_trace(mVcdFile, edge3_2_6_fu_62, "edge3_2_6_fu_62");
    sc_trace(mVcdFile, tmp_126_fu_516_p1, "tmp_126_fu_516_p1");
    sc_trace(mVcdFile, edge3_2_7_fu_66, "edge3_2_7_fu_66");
    sc_trace(mVcdFile, edge3_2_8_fu_70, "edge3_2_8_fu_70");
    sc_trace(mVcdFile, a_1_fu_74, "a_1_fu_74");
    sc_trace(mVcdFile, a_3_fu_509_p2, "a_3_fu_509_p2");
    sc_trace(mVcdFile, x_fu_78, "x_fu_78");
    sc_trace(mVcdFile, temp_fu_82, "temp_fu_82");
    sc_trace(mVcdFile, edge3_0_2_fu_673_p3, "edge3_0_2_fu_673_p3");
    sc_trace(mVcdFile, edge3_1_3_fu_86, "edge3_1_3_fu_86");
    sc_trace(mVcdFile, edge3_1_fu_666_p3, "edge3_1_fu_666_p3");
    sc_trace(mVcdFile, edge3_2_9_fu_90, "edge3_2_9_fu_90");
    sc_trace(mVcdFile, edge3_2_fu_659_p3, "edge3_2_fu_659_p3");
    sc_trace(mVcdFile, tmp_182_fu_413_p2, "tmp_182_fu_413_p2");
    sc_trace(mVcdFile, tmp_183_fu_419_p2, "tmp_183_fu_419_p2");
    sc_trace(mVcdFile, p_lshr_f_i_cast_fu_442_p4, "p_lshr_f_i_cast_fu_442_p4");
    sc_trace(mVcdFile, tmp_i_cast_fu_452_p1, "tmp_i_cast_fu_452_p1");
    sc_trace(mVcdFile, tmp_379_i_fu_456_p2, "tmp_379_i_fu_456_p2");
    sc_trace(mVcdFile, k_assign_3_fu_462_p2, "k_assign_3_fu_462_p2");
    sc_trace(mVcdFile, p_k_i_fu_467_p3, "p_k_i_fu_467_p3");
    sc_trace(mVcdFile, j_1_cast_fu_532_p1, "j_1_cast_fu_532_p1");
    sc_trace(mVcdFile, tmp_187_fu_542_p2, "tmp_187_fu_542_p2");
    sc_trace(mVcdFile, tmp_fu_558_p2, "tmp_fu_558_p2");
    sc_trace(mVcdFile, tmp_123_fu_564_p2, "tmp_123_fu_564_p2");
    sc_trace(mVcdFile, tmp_185_fu_570_p2, "tmp_185_fu_570_p2");
    sc_trace(mVcdFile, tmp_125_fu_580_p1, "tmp_125_fu_580_p1");
    sc_trace(mVcdFile, tmp_124_fu_576_p1, "tmp_124_fu_576_p1");
    sc_trace(mVcdFile, edge3_load_phi_fu_596_p3, "edge3_load_phi_fu_596_p3");
    sc_trace(mVcdFile, tmp_228_cast_fu_603_p1, "tmp_228_cast_fu_603_p1");
    sc_trace(mVcdFile, cond_i_fu_642_p2, "cond_i_fu_642_p2");
    sc_trace(mVcdFile, tmp_190_fu_699_p0, "tmp_190_fu_699_p0");
    sc_trace(mVcdFile, grp_fu_498_ap_start, "grp_fu_498_ap_start");
    sc_trace(mVcdFile, grp_fu_498_ap_done, "grp_fu_498_ap_done");
    sc_trace(mVcdFile, tmp_186_fu_584_p2, "tmp_186_fu_584_p2");
    sc_trace(mVcdFile, ap_return_preg, "ap_return_preg");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, tmp_190_fu_699_p00, "tmp_190_fu_699_p00");
#endif

    }
}

getUBtoDF::~getUBtoDF() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete solution_sdiv_32nkbM_U43;
}

void getUBtoDF::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void getUBtoDF::thread_ap_clk_no_reset_() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state41.read()) && 
          esl_seteq<1,1,1>(or_cond_reg_799.read(), ap_const_lv1_1) && 
          esl_seteq<1,2,2>(ap_const_lv2_0, tmp_126_fu_516_p1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state41.read()) && 
          esl_seteq<1,1,1>(or_cond_reg_799.read(), ap_const_lv1_1) && 
          esl_seteq<1,2,2>(ap_const_lv2_1, tmp_126_fu_516_p1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state41.read()) && 
          esl_seteq<1,1,1>(or_cond_reg_799.read(), ap_const_lv1_1) && 
          !esl_seteq<1,2,2>(ap_const_lv2_0, tmp_126_fu_516_p1.read()) && 
          !esl_seteq<1,2,2>(ap_const_lv2_1, tmp_126_fu_516_p1.read())))) {
        a_1_fu_74 = a_3_fu_509_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        a_1_fu_74 = ap_const_lv32_0;
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_preg = ap_const_lv16_0;
    } else {
        if ((esl_seteq<1,1,1>(tmp_184_fu_536_p2.read(), ap_const_lv1_1) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state42.read()))) {
            ap_return_preg = tmp_186_fu_584_p2.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state44.read()) && 
         esl_seteq<1,1,1>(exitcond1_fu_630_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,2,2>(ap_phi_mux_i_i1_phi_fu_260_p4.read(), ap_const_lv2_1))) {
        arr1_i_be_reg_299 = arr_load_phi_i_fu_648_p3.read();
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state44.read()) && 
                 esl_seteq<1,1,1>(exitcond1_fu_630_p2.read(), ap_const_lv1_0) && 
                 !esl_seteq<1,2,2>(ap_const_lv2_0, ap_phi_mux_i_i1_phi_fu_260_p4.read()) && 
                 !esl_seteq<1,2,2>(ap_phi_mux_i_i1_phi_fu_260_p4.read(), ap_const_lv2_1)) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state44.read()) && 
                 esl_seteq<1,1,1>(exitcond1_fu_630_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,2,2>(ap_const_lv2_0, ap_phi_mux_i_i1_phi_fu_260_p4.read())))) {
        arr1_i_be_reg_299 = arr1_i_reg_234.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state45.read())) {
        arr1_i_reg_234 = arr1_i_be_reg_299.read();
    } else if ((esl_seteq<1,1,1>(tmp_188_fu_607_p2.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read()))) {
        arr1_i_reg_234 = edge3_1_3_fu_86.read();
    }
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state44.read()) && 
          esl_seteq<1,1,1>(exitcond1_fu_630_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,2,2>(ap_phi_mux_i_i1_phi_fu_260_p4.read(), ap_const_lv2_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state44.read()) && 
          esl_seteq<1,1,1>(exitcond1_fu_630_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,2,2>(ap_const_lv2_0, ap_phi_mux_i_i1_phi_fu_260_p4.read())))) {
        arr2_i_be_reg_267 = arr2_i_reg_212.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state44.read()) && 
                esl_seteq<1,1,1>(exitcond1_fu_630_p2.read(), ap_const_lv1_0) && 
                !esl_seteq<1,2,2>(ap_const_lv2_0, ap_phi_mux_i_i1_phi_fu_260_p4.read()) && 
                !esl_seteq<1,2,2>(ap_phi_mux_i_i1_phi_fu_260_p4.read(), ap_const_lv2_1))) {
        arr2_i_be_reg_267 = arr_load_phi_i_fu_648_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state45.read())) {
        arr2_i_reg_212 = arr2_i_be_reg_267.read();
    } else if ((esl_seteq<1,1,1>(tmp_188_fu_607_p2.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read()))) {
        arr2_i_reg_212 = edge3_2_9_fu_90.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state44.read()) && 
         esl_seteq<1,1,1>(exitcond1_fu_630_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,2,2>(ap_const_lv2_0, ap_phi_mux_i_i1_phi_fu_260_p4.read()))) {
        arr_i_be_reg_314 = arr_load_phi_i_fu_648_p3.read();
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state44.read()) && 
                 esl_seteq<1,1,1>(exitcond1_fu_630_p2.read(), ap_const_lv1_0) && 
                 !esl_seteq<1,2,2>(ap_const_lv2_0, ap_phi_mux_i_i1_phi_fu_260_p4.read()) && 
                 !esl_seteq<1,2,2>(ap_phi_mux_i_i1_phi_fu_260_p4.read(), ap_const_lv2_1)) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state44.read()) && 
                 esl_seteq<1,1,1>(exitcond1_fu_630_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,2,2>(ap_phi_mux_i_i1_phi_fu_260_p4.read(), ap_const_lv2_1)))) {
        arr_i_be_reg_314 = arr_i_reg_244.read();
    }
    if ((esl_seteq<1,1,1>(exitcond_fu_381_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        b_reg_188 = ap_const_lv32_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state47.read())) {
        b_reg_188 = b_3_fu_711_p2.read();
    }
    if ((esl_seteq<1,1,1>(exitcond1_fu_630_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state44.read()))) {
        edge3_1_3_fu_86 = edge3_1_fu_666_p3.read();
    } else if ((esl_seteq<1,1,1>(exitcond_fu_381_p2.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        edge3_1_3_fu_86 = edge3_2_7_fu_66.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state41.read()) && 
         esl_seteq<1,1,1>(or_cond_reg_799.read(), ap_const_lv1_1) && 
         esl_seteq<1,2,2>(ap_const_lv2_0, tmp_126_fu_516_p1.read()))) {
        edge3_2_6_fu_62 = edge3_0_reg_792.read();
    } else if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        edge3_2_6_fu_62 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state41.read()) && 
         esl_seteq<1,1,1>(or_cond_reg_799.read(), ap_const_lv1_1) && 
         esl_seteq<1,2,2>(ap_const_lv2_1, tmp_126_fu_516_p1.read()))) {
        edge3_2_7_fu_66 = edge3_0_reg_792.read();
    } else if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        edge3_2_7_fu_66 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state41.read()) && 
         esl_seteq<1,1,1>(or_cond_reg_799.read(), ap_const_lv1_1) && 
         !esl_seteq<1,2,2>(ap_const_lv2_0, tmp_126_fu_516_p1.read()) && 
         !esl_seteq<1,2,2>(ap_const_lv2_1, tmp_126_fu_516_p1.read()))) {
        edge3_2_8_fu_70 = edge3_0_reg_792.read();
    } else if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        edge3_2_8_fu_70 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(exitcond1_fu_630_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state44.read()))) {
        edge3_2_9_fu_90 = edge3_2_fu_659_p3.read();
    } else if ((esl_seteq<1,1,1>(exitcond_fu_381_p2.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        edge3_2_9_fu_90 = edge3_2_8_fu_70.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state45.read())) {
        i_i1_reg_256 = i_29_reg_888.read();
    } else if ((esl_seteq<1,1,1>(tmp_188_fu_607_p2.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read()))) {
        i_i1_reg_256 = ap_const_lv2_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state40.read())) {
        i_i_reg_131 = i_28_reg_824.read();
    } else if ((esl_seteq<1,1,1>(or_cond_fu_425_p2.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(tmp_i_fu_437_p2.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        i_i_reg_131 = n_assign_cast4_reg_751.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state41.read())) {
        i_reg_107 = j_10_reg_761.read();
    } else if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        i_reg_107 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(exitcond_fu_381_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        indvars_iv_reg_164 = ap_const_lv2_2;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state47.read())) {
        indvars_iv_reg_164 = indvars_iv_next_reg_905.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state40.read())) {
        j_i_reg_119 = j_9_reg_829.read();
    } else if ((esl_seteq<1,1,1>(or_cond_fu_425_p2.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(tmp_i_fu_437_p2.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        j_i_reg_119 = ap_const_lv32_1;
    }
    if ((esl_seteq<1,1,1>(exitcond1_fu_630_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state44.read()))) {
        k_reg_200 = k_3_reg_870.read();
    } else if ((esl_seteq<1,1,1>(tmp_184_fu_536_p2.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state42.read()))) {
        k_reg_200 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(exitcond_i_fu_481_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        p_0_i_reg_152 = s_i_reg_140.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(or_cond_fu_425_p2.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(tmp_i_fu_437_p2.read(), ap_const_lv1_1))) {
        p_0_i_reg_152 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(exitcond_fu_381_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        r_assign_reg_176 = ap_const_lv2_2;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state47.read())) {
        r_assign_reg_176 = j_reg_880.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state40.read())) {
        s_i_reg_140 = grp_fu_498_p2.read();
    } else if ((esl_seteq<1,1,1>(or_cond_fu_425_p2.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(tmp_i_fu_437_p2.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        s_i_reg_140 = ap_const_lv32_1;
    }
    if ((esl_seteq<1,1,1>(exitcond1_fu_630_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state44.read()))) {
        temp_fu_82 = edge3_0_2_fu_673_p3.read();
    } else if ((esl_seteq<1,1,1>(exitcond_fu_381_p2.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        temp_fu_82 = edge3_2_6_fu_62.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state44.read()) && 
         esl_seteq<1,1,1>(exitcond1_fu_630_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,2,2>(ap_const_lv2_0, ap_phi_mux_i_i1_phi_fu_260_p4.read()))) {
        write_flag_i_be_reg_282 = ap_const_lv1_1;
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state44.read()) && 
                 esl_seteq<1,1,1>(exitcond1_fu_630_p2.read(), ap_const_lv1_0) && 
                 !esl_seteq<1,2,2>(ap_const_lv2_0, ap_phi_mux_i_i1_phi_fu_260_p4.read()) && 
                 !esl_seteq<1,2,2>(ap_phi_mux_i_i1_phi_fu_260_p4.read(), ap_const_lv2_1)) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state44.read()) && 
                 esl_seteq<1,1,1>(exitcond1_fu_630_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,2,2>(ap_phi_mux_i_i1_phi_fu_260_p4.read(), ap_const_lv2_1)))) {
        write_flag_i_be_reg_282 = write_flag_i_reg_222.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state45.read())) {
        write_flag_i_reg_222 = write_flag_i_be_reg_282.read();
    } else if ((esl_seteq<1,1,1>(tmp_188_fu_607_p2.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read()))) {
        write_flag_i_reg_222 = ap_const_lv1_0;
    }
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state41.read()) && 
          esl_seteq<1,1,1>(or_cond_reg_799.read(), ap_const_lv1_1) && 
          esl_seteq<1,2,2>(ap_const_lv2_0, tmp_126_fu_516_p1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state41.read()) && 
          esl_seteq<1,1,1>(or_cond_reg_799.read(), ap_const_lv1_1) && 
          esl_seteq<1,2,2>(ap_const_lv2_1, tmp_126_fu_516_p1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state41.read()) && 
          esl_seteq<1,1,1>(or_cond_reg_799.read(), ap_const_lv1_1) && 
          !esl_seteq<1,2,2>(ap_const_lv2_0, tmp_126_fu_516_p1.read()) && 
          !esl_seteq<1,2,2>(ap_const_lv2_1, tmp_126_fu_516_p1.read())))) {
        x_fu_78 = x_4_reg_803.read();
    } else if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        x_fu_78 = ap_const_lv32_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state45.read())) {
        arr_i_reg_244 = arr_i_be_reg_314.read();
    }
    if ((esl_seteq<1,1,1>(tmp_184_fu_536_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state42.read()))) {
        cond2_reg_850 = cond2_fu_552_p2.read();
        tmp_225_cast_reg_845 = tmp_225_cast_fu_548_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        edge3_0_reg_792 = cubiecube_0_ep_q0.read();
        or_cond_reg_799 = or_cond_fu_425_p2.read();
    }
    if ((esl_seteq<1,1,1>(exitcond_i_fu_481_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        i_28_reg_824 = i_28_fu_492_p2.read();
        s_reg_819 = s_fu_486_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state44.read())) {
        i_29_reg_888 = i_29_fu_636_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state46.read())) {
        indvars_iv_next_reg_905 = indvars_iv_next_fu_705_p2.read();
        tmp_190_reg_900 = tmp_190_fu_699_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        j_10_reg_761 = j_10_fu_387_p2.read();
        n_assign_cast4_reg_751 = n_assign_cast4_fu_377_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        j_9_reg_829 = j_9_fu_503_p2.read();
    }
    if ((esl_seteq<1,1,1>(tmp_188_fu_607_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read()))) {
        j_reg_880 = j_fu_624_p2.read();
        tmp_189_reg_875 = tmp_189_fu_618_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read())) {
        k_3_reg_870 = k_3_fu_612_p2.read();
    }
    if ((esl_seteq<1,1,1>(or_cond_fu_425_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(tmp_i_fu_437_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        tmp_380_i_reg_811 = tmp_380_i_fu_475_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(or_cond_fu_425_p2.read(), ap_const_lv1_1))) {
        x_4_reg_803 = x_4_fu_431_p2.read();
    }
}

void getUBtoDF::thread_a_3_fu_509_p2() {
    a_3_fu_509_p2 = (!p_0_i_reg_152.read().is_01() || !a_1_fu_74.read().is_01())? sc_lv<32>(): (sc_biguint<32>(p_0_i_reg_152.read()) + sc_biguint<32>(a_1_fu_74.read()));
}

void getUBtoDF::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void getUBtoDF::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void getUBtoDF::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void getUBtoDF::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void getUBtoDF::thread_ap_CS_fsm_state40() {
    ap_CS_fsm_state40 = ap_CS_fsm.read()[39];
}

void getUBtoDF::thread_ap_CS_fsm_state41() {
    ap_CS_fsm_state41 = ap_CS_fsm.read()[40];
}

void getUBtoDF::thread_ap_CS_fsm_state42() {
    ap_CS_fsm_state42 = ap_CS_fsm.read()[41];
}

void getUBtoDF::thread_ap_CS_fsm_state43() {
    ap_CS_fsm_state43 = ap_CS_fsm.read()[42];
}

void getUBtoDF::thread_ap_CS_fsm_state44() {
    ap_CS_fsm_state44 = ap_CS_fsm.read()[43];
}

void getUBtoDF::thread_ap_CS_fsm_state45() {
    ap_CS_fsm_state45 = ap_CS_fsm.read()[44];
}

void getUBtoDF::thread_ap_CS_fsm_state46() {
    ap_CS_fsm_state46 = ap_CS_fsm.read()[45];
}

void getUBtoDF::thread_ap_CS_fsm_state47() {
    ap_CS_fsm_state47 = ap_CS_fsm.read()[46];
}

void getUBtoDF::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void getUBtoDF::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(tmp_184_fu_536_p2.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state42.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void getUBtoDF::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void getUBtoDF::thread_ap_phi_mux_i_i1_phi_fu_260_p4() {
    ap_phi_mux_i_i1_phi_fu_260_p4 = i_i1_reg_256.read();
}

void getUBtoDF::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(tmp_184_fu_536_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state42.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void getUBtoDF::thread_ap_return() {
    if ((esl_seteq<1,1,1>(tmp_184_fu_536_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state42.read()))) {
        ap_return = tmp_186_fu_584_p2.read();
    } else {
        ap_return = ap_return_preg.read();
    }
}

void getUBtoDF::thread_arr_load_phi_i_fu_648_p3() {
    arr_load_phi_i_fu_648_p3 = (!cond_i_fu_642_p2.read()[0].is_01())? sc_lv<4>(): ((cond_i_fu_642_p2.read()[0].to_bool())? arr1_i_reg_234.read(): arr2_i_reg_212.read());
}

void getUBtoDF::thread_b_3_fu_711_p2() {
    b_3_fu_711_p2 = (!k_reg_200.read().is_01() || !tmp_190_reg_900.read().is_01())? sc_lv<32>(): (sc_biguint<32>(k_reg_200.read()) + sc_biguint<32>(tmp_190_reg_900.read()));
}

void getUBtoDF::thread_cond2_fu_552_p2() {
    cond2_fu_552_p2 = (!r_assign_reg_176.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(r_assign_reg_176.read() == ap_const_lv2_1);
}

void getUBtoDF::thread_cond_i_fu_642_p2() {
    cond_i_fu_642_p2 = (!i_i1_reg_256.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(i_i1_reg_256.read() == ap_const_lv2_0);
}

void getUBtoDF::thread_cubiecube_0_ep_address0() {
    cubiecube_0_ep_address0 =  (sc_lv<4>) (tmp_s_fu_393_p1.read());
}

void getUBtoDF::thread_cubiecube_0_ep_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        cubiecube_0_ep_ce0 = ap_const_logic_1;
    } else {
        cubiecube_0_ep_ce0 = ap_const_logic_0;
    }
}

void getUBtoDF::thread_edge3_0_2_fu_673_p3() {
    edge3_0_2_fu_673_p3 = (!write_flag_i_reg_222.read()[0].is_01())? sc_lv<4>(): ((write_flag_i_reg_222.read()[0].to_bool())? arr_i_reg_244.read(): temp_fu_82.read());
}

void getUBtoDF::thread_edge3_1_fu_666_p3() {
    edge3_1_fu_666_p3 = (!cond2_reg_850.read()[0].is_01())? sc_lv<4>(): ((cond2_reg_850.read()[0].to_bool())? temp_fu_82.read(): arr1_i_reg_234.read());
}

void getUBtoDF::thread_edge3_2_fu_659_p3() {
    edge3_2_fu_659_p3 = (!cond2_reg_850.read()[0].is_01())? sc_lv<4>(): ((cond2_reg_850.read()[0].to_bool())? arr2_i_reg_212.read(): temp_fu_82.read());
}

void getUBtoDF::thread_edge3_load_phi_fu_596_p3() {
    edge3_load_phi_fu_596_p3 = (!cond2_reg_850.read()[0].is_01())? sc_lv<4>(): ((cond2_reg_850.read()[0].to_bool())? edge3_1_3_fu_86.read(): edge3_2_9_fu_90.read());
}

void getUBtoDF::thread_exitcond1_fu_630_p2() {
    exitcond1_fu_630_p2 = (!i_i1_reg_256.read().is_01() || !indvars_iv_reg_164.read().is_01())? sc_lv<1>(): sc_lv<1>(i_i1_reg_256.read() == indvars_iv_reg_164.read());
}

void getUBtoDF::thread_exitcond_fu_381_p2() {
    exitcond_fu_381_p2 = (!i_reg_107.read().is_01() || !ap_const_lv4_C.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_107.read() == ap_const_lv4_C);
}

void getUBtoDF::thread_exitcond_i_fu_481_p2() {
    exitcond_i_fu_481_p2 = (!j_i_reg_119.read().is_01() || !tmp_380_i_reg_811.read().is_01())? sc_lv<1>(): sc_lv<1>(j_i_reg_119.read() == tmp_380_i_reg_811.read());
}

void getUBtoDF::thread_grp_fu_498_ap_start() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        grp_fu_498_ap_start = ap_const_logic_1;
    } else {
        grp_fu_498_ap_start = ap_const_logic_0;
    }
}

void getUBtoDF::thread_i_28_fu_492_p2() {
    i_28_fu_492_p2 = (!i_i_reg_131.read().is_01() || !ap_const_lv32_FFFFFFFF.is_01())? sc_lv<32>(): (sc_bigint<32>(i_i_reg_131.read()) + sc_bigint<32>(ap_const_lv32_FFFFFFFF));
}

void getUBtoDF::thread_i_29_fu_636_p2() {
    i_29_fu_636_p2 = (!i_i1_reg_256.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(i_i1_reg_256.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void getUBtoDF::thread_indvars_iv_next_fu_705_p2() {
    indvars_iv_next_fu_705_p2 = (!indvars_iv_reg_164.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<2>(): (sc_biguint<2>(indvars_iv_reg_164.read()) + sc_bigint<2>(ap_const_lv2_3));
}

void getUBtoDF::thread_j_10_fu_387_p2() {
    j_10_fu_387_p2 = (!i_reg_107.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i_reg_107.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void getUBtoDF::thread_j_1_cast_fu_532_p1() {
    j_1_cast_fu_532_p1 = esl_zext<3,2>(r_assign_reg_176.read());
}

void getUBtoDF::thread_j_9_fu_503_p2() {
    j_9_fu_503_p2 = (!j_i_reg_119.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(j_i_reg_119.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void getUBtoDF::thread_j_fu_624_p2() {
    j_fu_624_p2 = (!r_assign_reg_176.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<2>(): (sc_biguint<2>(r_assign_reg_176.read()) + sc_bigint<2>(ap_const_lv2_3));
}

void getUBtoDF::thread_k_3_fu_612_p2() {
    k_3_fu_612_p2 = (!k_reg_200.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(k_reg_200.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void getUBtoDF::thread_k_assign_3_fu_462_p2() {
    k_assign_3_fu_462_p2 = (!n_assign_cast4_reg_751.read().is_01() || !x_4_fu_431_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(n_assign_cast4_reg_751.read()) - sc_biguint<32>(x_4_fu_431_p2.read()));
}

void getUBtoDF::thread_n_assign_cast4_fu_377_p1() {
    n_assign_cast4_fu_377_p1 = esl_zext<32,4>(i_reg_107.read());
}

void getUBtoDF::thread_or_cond_fu_425_p2() {
    or_cond_fu_425_p2 = (tmp_182_fu_413_p2.read() & tmp_183_fu_419_p2.read());
}

void getUBtoDF::thread_p_k_i_fu_467_p3() {
    p_k_i_fu_467_p3 = (!tmp_379_i_fu_456_p2.read()[0].is_01())? sc_lv<32>(): ((tmp_379_i_fu_456_p2.read()[0].to_bool())? k_assign_3_fu_462_p2.read(): x_4_fu_431_p2.read());
}

void getUBtoDF::thread_p_lshr_f_i_cast_fu_442_p4() {
    p_lshr_f_i_cast_fu_442_p4 = i_reg_107.read().range(3, 1);
}

void getUBtoDF::thread_s_fu_486_p2() {
    s_fu_486_p2 = (!s_i_reg_140.read().is_01() || !i_i_reg_131.read().is_01())? sc_lv<32>(): sc_bigint<32>(s_i_reg_140.read()) * sc_bigint<32>(i_i_reg_131.read());
}

void getUBtoDF::thread_tmp_123_fu_564_p2() {
    tmp_123_fu_564_p2 = (!ap_const_lv32_1.is_01())? sc_lv<32>(): a_1_fu_74.read() << (unsigned short)ap_const_lv32_1.to_uint();
}

void getUBtoDF::thread_tmp_124_fu_576_p1() {
    tmp_124_fu_576_p1 = b_reg_188.read().range(16-1, 0);
}

void getUBtoDF::thread_tmp_125_fu_580_p1() {
    tmp_125_fu_580_p1 = tmp_185_fu_570_p2.read().range(16-1, 0);
}

void getUBtoDF::thread_tmp_126_fu_516_p1() {
    tmp_126_fu_516_p1 = x_fu_78.read().range(2-1, 0);
}

void getUBtoDF::thread_tmp_182_fu_413_p2() {
    tmp_182_fu_413_p2 = (!cubiecube_0_ep_q0.read().is_01() || !ap_const_lv4_2.is_01())? sc_lv<1>(): (sc_biguint<4>(cubiecube_0_ep_q0.read()) > sc_biguint<4>(ap_const_lv4_2));
}

void getUBtoDF::thread_tmp_183_fu_419_p2() {
    tmp_183_fu_419_p2 = (!cubiecube_0_ep_q0.read().is_01() || !ap_const_lv4_6.is_01())? sc_lv<1>(): (sc_biguint<4>(cubiecube_0_ep_q0.read()) < sc_biguint<4>(ap_const_lv4_6));
}

void getUBtoDF::thread_tmp_184_fu_536_p2() {
    tmp_184_fu_536_p2 = (!r_assign_reg_176.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(r_assign_reg_176.read() == ap_const_lv2_0);
}

void getUBtoDF::thread_tmp_185_fu_570_p2() {
    tmp_185_fu_570_p2 = (!tmp_fu_558_p2.read().is_01() || !tmp_123_fu_564_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp_fu_558_p2.read()) - sc_biguint<32>(tmp_123_fu_564_p2.read()));
}

void getUBtoDF::thread_tmp_186_fu_584_p2() {
    tmp_186_fu_584_p2 = (!tmp_125_fu_580_p1.read().is_01() || !tmp_124_fu_576_p1.read().is_01())? sc_lv<16>(): (sc_biguint<16>(tmp_125_fu_580_p1.read()) + sc_biguint<16>(tmp_124_fu_576_p1.read()));
}

void getUBtoDF::thread_tmp_187_fu_542_p2() {
    tmp_187_fu_542_p2 = (!j_1_cast_fu_532_p1.read().is_01() || !ap_const_lv3_3.is_01())? sc_lv<3>(): (sc_biguint<3>(j_1_cast_fu_532_p1.read()) + sc_biguint<3>(ap_const_lv3_3));
}

void getUBtoDF::thread_tmp_188_fu_607_p2() {
    tmp_188_fu_607_p2 = (!tmp_228_cast_fu_603_p1.read().is_01() || !tmp_225_cast_reg_845.read().is_01())? sc_lv<1>(): sc_lv<1>(tmp_228_cast_fu_603_p1.read() == tmp_225_cast_reg_845.read());
}

void getUBtoDF::thread_tmp_189_fu_618_p2() {
    tmp_189_fu_618_p2 = (!r_assign_reg_176.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(r_assign_reg_176.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void getUBtoDF::thread_tmp_190_fu_699_p0() {
    tmp_190_fu_699_p0 =  (sc_lv<2>) (tmp_190_fu_699_p00.read());
}

void getUBtoDF::thread_tmp_190_fu_699_p00() {
    tmp_190_fu_699_p00 = esl_zext<32,2>(tmp_189_reg_875.read());
}

void getUBtoDF::thread_tmp_190_fu_699_p2() {
    tmp_190_fu_699_p2 = (!tmp_190_fu_699_p0.read().is_01() || !b_reg_188.read().is_01())? sc_lv<32>(): sc_biguint<2>(tmp_190_fu_699_p0.read()) * sc_bigint<32>(b_reg_188.read());
}

void getUBtoDF::thread_tmp_225_cast_fu_548_p1() {
    tmp_225_cast_fu_548_p1 = esl_zext<5,3>(tmp_187_fu_542_p2.read());
}

void getUBtoDF::thread_tmp_228_cast_fu_603_p1() {
    tmp_228_cast_fu_603_p1 = esl_zext<5,4>(edge3_load_phi_fu_596_p3.read());
}

void getUBtoDF::thread_tmp_379_i_fu_456_p2() {
    tmp_379_i_fu_456_p2 = (!tmp_i_cast_fu_452_p1.read().is_01() || !x_4_fu_431_p2.read().is_01())? sc_lv<1>(): (sc_bigint<32>(tmp_i_cast_fu_452_p1.read()) < sc_bigint<32>(x_4_fu_431_p2.read()));
}

void getUBtoDF::thread_tmp_380_i_fu_475_p2() {
    tmp_380_i_fu_475_p2 = (!p_k_i_fu_467_p3.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(p_k_i_fu_467_p3.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void getUBtoDF::thread_tmp_fu_558_p2() {
    tmp_fu_558_p2 = (!ap_const_lv32_3.is_01())? sc_lv<32>(): a_1_fu_74.read() << (unsigned short)ap_const_lv32_3.to_uint();
}

void getUBtoDF::thread_tmp_i_cast_fu_452_p1() {
    tmp_i_cast_fu_452_p1 = esl_zext<32,3>(p_lshr_f_i_cast_fu_442_p4.read());
}

void getUBtoDF::thread_tmp_i_fu_437_p2() {
    tmp_i_fu_437_p2 = (!n_assign_cast4_reg_751.read().is_01() || !x_4_fu_431_p2.read().is_01())? sc_lv<1>(): (sc_bigint<32>(n_assign_cast4_reg_751.read()) < sc_bigint<32>(x_4_fu_431_p2.read()));
}

void getUBtoDF::thread_tmp_s_fu_393_p1() {
    tmp_s_fu_393_p1 = esl_zext<64,4>(i_reg_107.read());
}

void getUBtoDF::thread_x_4_fu_431_p2() {
    x_4_fu_431_p2 = (!x_fu_78.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(x_fu_78.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void getUBtoDF::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(exitcond_fu_381_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state42;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(or_cond_fu_425_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(tmp_i_fu_437_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state41;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(exitcond_i_fu_481_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
                ap_NS_fsm = ap_ST_fsm_state41;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state20;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_fsm_state21;
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_fsm_state22;
            break;
        case 2097152 : 
            ap_NS_fsm = ap_ST_fsm_state23;
            break;
        case 4194304 : 
            ap_NS_fsm = ap_ST_fsm_state24;
            break;
        case 8388608 : 
            ap_NS_fsm = ap_ST_fsm_state25;
            break;
        case 16777216 : 
            ap_NS_fsm = ap_ST_fsm_state26;
            break;
        case 33554432 : 
            ap_NS_fsm = ap_ST_fsm_state27;
            break;
        case 67108864 : 
            ap_NS_fsm = ap_ST_fsm_state28;
            break;
        case 134217728 : 
            ap_NS_fsm = ap_ST_fsm_state29;
            break;
        case 268435456 : 
            ap_NS_fsm = ap_ST_fsm_state30;
            break;
        case 536870912 : 
            ap_NS_fsm = ap_ST_fsm_state31;
            break;
        case 1073741824 : 
            ap_NS_fsm = ap_ST_fsm_state32;
            break;
        case 2147483648 : 
            ap_NS_fsm = ap_ST_fsm_state33;
            break;
        case 4294967296 : 
            ap_NS_fsm = ap_ST_fsm_state34;
            break;
        case 8589934592 : 
            ap_NS_fsm = ap_ST_fsm_state35;
            break;
        case 17179869184 : 
            ap_NS_fsm = ap_ST_fsm_state36;
            break;
        case 34359738368 : 
            ap_NS_fsm = ap_ST_fsm_state37;
            break;
        case 68719476736 : 
            ap_NS_fsm = ap_ST_fsm_state38;
            break;
        case 137438953472 : 
            ap_NS_fsm = ap_ST_fsm_state39;
            break;
        case 274877906944 : 
            ap_NS_fsm = ap_ST_fsm_state40;
            break;
        case 549755813888 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 1099511627776 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        case 2199023255552 : 
            if ((esl_seteq<1,1,1>(tmp_184_fu_536_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state42.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state43;
            }
            break;
        case 4398046511104 : 
            if ((esl_seteq<1,1,1>(tmp_188_fu_607_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read()))) {
                ap_NS_fsm = ap_ST_fsm_state44;
            } else {
                ap_NS_fsm = ap_ST_fsm_state46;
            }
            break;
        case 8796093022208 : 
            if ((esl_seteq<1,1,1>(exitcond1_fu_630_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state44.read()))) {
                ap_NS_fsm = ap_ST_fsm_state43;
            } else {
                ap_NS_fsm = ap_ST_fsm_state45;
            }
            break;
        case 17592186044416 : 
            ap_NS_fsm = ap_ST_fsm_state44;
            break;
        case 35184372088832 : 
            ap_NS_fsm = ap_ST_fsm_state47;
            break;
        case 70368744177664 : 
            ap_NS_fsm = ap_ST_fsm_state42;
            break;
        default : 
            ap_NS_fsm = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            break;
    }
}

}

