// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __toCubieCube_edgeFfYi_H__
#define __toCubieCube_edgeFfYi_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct toCubieCube_edgeFfYi_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 6;
  static const unsigned AddressRange = 12;
  static const unsigned AddressWidth = 4;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(toCubieCube_edgeFfYi_ram) {
        ram[0] = "0b001010";
        ram[1] = "0b010011";
        ram[2] = "0b100101";
        ram[3] = "0b101110";
        ram[4] = "0b010000";
        ram[5] = "0b011001";
        ram[6] = "0b101011";
        ram[7] = "0b110100";
        ram[8] = "0b001100";
        ram[9] = "0b101001";
        ram[10] = "0b100111";
        ram[11] = "0b001110";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(toCubieCube_edgeFfYi) {


static const unsigned DataWidth = 6;
static const unsigned AddressRange = 12;
static const unsigned AddressWidth = 4;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


toCubieCube_edgeFfYi_ram* meminst;


SC_CTOR(toCubieCube_edgeFfYi) {
meminst = new toCubieCube_edgeFfYi_ram("toCubieCube_edgeFfYi_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~toCubieCube_edgeFfYi() {
    delete meminst;
}


};//endmodule
#endif
