#!/bin/bash

# kociemba DRLUUBFBRBLURRLRUBLRDDFDLFUFUFFDBRDUBRUFLLFDDBFLUBLRBD
# kociemba FLBUULFFLFDURRDBUBUUDDFFBRDDBLRDRFLLRLRULFUDRRBDBBBUFL
# kociemba BBURUDBFUFFFRRFUUFLULUFUDLRRDBBDBDBLUDDFLLRRBRLLLBRDDF
# kociemba UUUUUUUUURRRRRRRRRFFFFFFFFFDDDDDDDDDLLLLLLLLLBBBBBBBBB

# for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 1 1 1 1 1 1 1 1 1 1 1
# do
#     bin/kociemba DRLUUBFBRBLURRLRUBLRDDFDLFUFUFFDBRDUBRUFLLFDDBFLUBLRBD
#     kociemba DRLUUBFBRBLURRLRUBLRDDFDLFUFUFFDBRDUBRUFLLFDDBFLUBLRBD

#     bin/kociemba FLBUULFFLFDURRDBUBUUDDFFBRDDBLRDRFLLRLRULFUDRRBDBBBUFL
#     kociemba FLBUULFFLFDURRDBUBUUDDFFBRDDBLRDRFLLRLRULFUDRRBDBBBUFL

#     bin/kociemba BBURUDBFUFFFRRFUUFLULUFUDLRRDBBDBDBLUDDFLLRRBRLLLBRDDF
#     kociemba BBURUDBFUFFFRRFUUFLULUFUDLRRDBBDBDBLUDDFLLRRBRLLLBRDDF

#     bin/kociemba LLLBUBLLLBRBURUBRBUUUFFFUUURRRFDFRRRFLFDLDFLFDDDBBBDDD
#     kociemba LLLBUBLLLBRBURUBRBUUUFFFUUURRRFDFRRRFLFDLDFLFDDDBBBDDD

#     bin/kociemba UFLFUBFRLBDBBRLFBRRUUFFUDBURLLDDRFLUBRDDLULRBDDRUBLFFD
#     kociemba UFLFUBFRLBDBBRLFBRRUUFFUDBURLLDDRFLUBRDDLULRBDDRUBLFFD

#     bin/kociemba FRRLUBUUBUDURRLLBBBLLUFBRRFDFUDDUDURDBRFLRLFFFDLDBLDFB
#     kociemba FRRLUBUUBUDURRLLBBBLLUFBRRFDFUDDUDURDBRFLRLFFFDLDBLDFB

#     bin/kociemba DBDRULDUBLBFDRRULFFBDLFRUDFBFRBDFULURURULUBRRLDBFBFLDL
#     kociemba DBDRULDUBLBFDRRULFFBDLFRUDFBFRBDFULURURULUBRRLDBFBFLDL
# done
bin/kociemba DRLUUBFBRBLURRLRUBLRDDFDLFUFUFFDBRDUBRUFLLFDDBFLUBLRBD
kociemba DRLUUBFBRBLURRLRUBLRDDFDLFUFUFFDBRDUBRUFLLFDDBFLUBLRBD
echo ""
bin/kociemba FLBUULFFLFDURRDBUBUUDDFFBRDDBLRDRFLLRLRULFUDRRBDBBBUFL
kociemba FLBUULFFLFDURRDBUBUUDDFFBRDDBLRDRFLLRLRULFUDRRBDBBBUFL
echo ""
bin/kociemba BBURUDBFUFFFRRFUUFLULUFUDLRRDBBDBDBLUDDFLLRRBRLLLBRDDF
kociemba BBURUDBFUFFFRRFUUFLULUFUDLRRDBBDBDBLUDDFLLRRBRLLLBRDDF
echo ""
bin/kociemba LLLBUBLLLBRBURUBRBUUUFFFUUURRRFDFRRRFLFDLDFLFDDDBBBDDD
kociemba LLLBUBLLLBRBURUBRBUUUFFFUUURRRFDFRRRFLFDLDFLFDDDBBBDDD
echo ""
bin/kociemba UFLFUBFRLBDBBRLFBRRUUFFUDBURLLDDRFLUBRDDLULRBDDRUBLFFD
kociemba UFLFUBFRLBDBBRLFBRRUUFFUDBURLLDDRFLUBRDDLULRBDDRUBLFFD
echo ""
bin/kociemba FRRLUBUUBUDURRLLBBBLLUFBRRFDFUDDUDURDBRFLRLFFFDLDBLDFB
kociemba FRRLUBUUBUDURRLLBBBLLUFBRRFDFUDDUDURDBRFLRLFFFDLDBLDFB
echo ""
bin/kociemba DBDRULDUBLBFDRRULFFBDLFRUDFBFRBDFULURURULUBRRLDBFBFLDL
kociemba DBDRULDUBLBFDRRULFFBDLFRUDFBFRBDFULURURULUBRRLDBFBFLDL
echo ""
bin/kociemba UUUUUUUUURRRRRRRRRFFFFFFFFFDDDDDDDDDLLLLLLLLLBBBBBBBBB
bin/kociemba BBBBBBBBBUUUUUUUUURRRRRRRRRFFFFFFFFFDDDDDDDDDLLLLLLLLL
bin/kociemba LLLLLLLLLBBBBBBBBBUUUUUUUUURRRRRRRRRFFFFFFFFFDDDDDDDDD
bin/kociemba DDDDDDDDDLLLLLLLLLBBBBBBBBBUUUUUUUUURRRRRRRRRFFFFFFFFF
bin/kociemba FFFFFFFFFDDDDDDDDDLLLLLLLLLBBBBBBBBBUUUUUUUUURRRRRRRRR
bin/kociemba RRRRRRRRRFFFFFFFFFDDDDDDDDDLLLLLLLLLBBBBBBBBBUUUUUUUUU

# val1=$(bin/kociemba DRLUUBFBRBLURRLRUBLRDDFDLFUFUFFDBRDUBRUFLLFDDBFLUBLRBD)
# val2=$(kociemba DRLUUBFBRBLURRLRUBLRDDFDLFUFUFFDBRDUBRUFLLFDDBFLUBLRBD)
# echo $val1
# echo $val2
# if [ $val1==$val2 ]
# then
#     echo "equal"
# fi

# bin/kociemba DRLUUBFBRBLURRLRUBLRDDFDLFUFUFFDBRDUBRUFLLFDDBFLUBLRBD > scripts/a.txt
# kociemba DRLUUBFBRBLURRLRUBLRDDFDLFUFUFFDBRDUBRUFLLFDDBFLUBLRBD > scripts/b.txt
# diff scripts/a.txt scripts/b.txt